package view;

import business.PesquisaAtletaBS;
import swing.SwingFrm;

/**
 *
 * @author nilto
 */
public class FrmPeaquisaAtleta extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmPeaquisaAtleta frmPeaquisaAluno;

    // Método gerenciador de janelas abertas
    public static FrmPeaquisaAtleta getInstancia() {
        if (frmPeaquisaAluno == null) {
            frmPeaquisaAluno = new FrmPeaquisaAtleta();
        }
        return frmPeaquisaAluno;
    }

    SwingFrm swingFrm = new SwingFrm();
    PesquisaAtletaBS pesquisaAtletaBS = new PesquisaAtletaBS();

    /**
     * Creates new form FrmPeaquisaAtleta
     */
    public FrmPeaquisaAtleta() {
        initComponents();

        tabelaPesquisaAtleta.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaPesquisaAtleta.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());

        txtNomePesquisaAtleta.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelPesquisa = new javax.swing.JPanel();
        txtTotalPesquisaAtleta = new app.bolivia.swing.JCTextField();
        lbTotalPesquisaAtleta = new swing.JLabelBordas();
        cmbClubePesquisaAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbClubePesquisaAtleta = new swing.JLabelBordas();
        txtNomePesquisaAtleta = new app.bolivia.swing.JCTextField();
        lbNomePesquisaAtleta = new swing.JLabelBordas();
        btnPesquisaAtleta = new javax.swing.JButton();
        btnLimparPesquisaAtleta = new javax.swing.JButton();
        jScrollPanePesquisaAtleta = new javax.swing.JScrollPane();
        tabelaPesquisaAtleta = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.black);
        setTitle("PESQUISAR ATLETA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISA DE ATLETA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelPesquisa.setForeground(new java.awt.Color(35, 102, 145));
        painelPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotalPesquisaAtleta.setEditable(false);
        txtTotalPesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtTotalPesquisaAtleta.setBorder(null);
        txtTotalPesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalPesquisaAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPesquisaAtleta.setToolTipText("");
        txtTotalPesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalPesquisaAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalPesquisaAtleta.setPlaceholder("TOTAL ATLETA");
        txtTotalPesquisaAtleta.setVerifyInputWhenFocusTarget(false);
        painelPesquisa.add(txtTotalPesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 33, 100, 30));

        lbTotalPesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbTotalPesquisaAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbTotalPesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalPesquisaAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalPesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotalPesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbTotalPesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, 120, 50));

        cmbClubePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbClubePesquisaAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbClubePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbClubePesquisaAtleta.setOpaque(false);
        cmbClubePesquisaAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClubePesquisaAtletaItemStateChanged(evt);
            }
        });
        painelPesquisa.add(cmbClubePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 310, -1));

        lbClubePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbClubePesquisaAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbClubePesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbClubePesquisaAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbClubePesquisaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/clube.png"))); // NOI18N
        lbClubePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClubePesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbClubePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 380, 50));

        txtNomePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtNomePesquisaAtleta.setBorder(null);
        txtNomePesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtNomePesquisaAtleta.setToolTipText("");
        txtNomePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomePesquisaAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomePesquisaAtleta.setPlaceholder("NOME DO ALUNO(A)");
        txtNomePesquisaAtleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomePesquisaAtletaKeyReleased(evt);
            }
        });
        painelPesquisa.add(txtNomePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 320, 30));

        lbNomePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbNomePesquisaAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbNomePesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbNomePesquisaAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNomePesquisaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/user.png"))); // NOI18N
        lbNomePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomePesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbNomePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 380, 50));

        btnPesquisaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisaAtleta.setForeground(new java.awt.Color(35, 102, 145));
        btnPesquisaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-1-50px.png"))); // NOI18N
        btnPesquisaAtleta.setText("PESQUISAR");
        btnPesquisaAtleta.setBorder(null);
        btnPesquisaAtleta.setBorderPainted(false);
        btnPesquisaAtleta.setContentAreaFilled(false);
        btnPesquisaAtleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisaAtleta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-2-50px.png"))); // NOI18N
        btnPesquisaAtleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisaAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAtletaActionPerformed(evt);
            }
        });
        painelPesquisa.add(btnPesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, -1));

        btnLimparPesquisaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparPesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparPesquisaAtleta.setForeground(new java.awt.Color(35, 102, 145));
        btnLimparPesquisaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimparPesquisaAtleta.setText("LIMPAR PESQUISA");
        btnLimparPesquisaAtleta.setBorder(null);
        btnLimparPesquisaAtleta.setBorderPainted(false);
        btnLimparPesquisaAtleta.setContentAreaFilled(false);
        btnLimparPesquisaAtleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparPesquisaAtleta.setEnabled(false);
        btnLimparPesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparPesquisaAtleta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimparPesquisaAtleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparPesquisaAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPesquisaAtletaActionPerformed(evt);
            }
        });
        painelPesquisa.add(btnLimparPesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 90, -1, -1));

        jScrollPanePesquisaAtleta.setPreferredSize(new java.awt.Dimension(500, 161));

        tabelaPesquisaAtleta = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaPesquisaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        tabelaPesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaPesquisaAtleta.setForeground(new java.awt.Color(35, 102, 145));
        tabelaPesquisaAtleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DANGAY", "ID YUDANSHA", "ID CBKSC", "CLUBE", "ALUNO(A)", "SEXO", "IDADE", "NASCIMENTO", "CATEGORIA", "FAIXA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisaAtleta.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaPesquisaAtleta.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaPesquisaAtleta.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaPesquisaAtleta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaPesquisaAtleta.getTableHeader().setReorderingAllowed(false);
        jScrollPanePesquisaAtleta.setViewportView(tabelaPesquisaAtleta);

        painelPesquisa.add(jScrollPanePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1300, 400));

        painelPrincipal.add(painelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1320, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1348, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePesquisaAtletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePesquisaAtletaKeyReleased
        txtNomePesquisaAtleta.setText(txtNomePesquisaAtleta.getText().toUpperCase());
        btnLimparPesquisaAtleta.setEnabled(true);
    }//GEN-LAST:event_txtNomePesquisaAtletaKeyReleased

    private void btnPesquisaAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAtletaActionPerformed
        pesquisaAtletaBS.pesquisarAtleta();
    }//GEN-LAST:event_btnPesquisaAtletaActionPerformed

    private void btnLimparPesquisaAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPesquisaAtletaActionPerformed
        // TODO add your handling code here:
        pesquisaAtletaBS.limparCampos();
    }//GEN-LAST:event_btnLimparPesquisaAtletaActionPerformed

    private void cmbClubePesquisaAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClubePesquisaAtletaItemStateChanged
        // TODO add your handling code here:
        btnLimparPesquisaAtleta.setEnabled(true);
    }//GEN-LAST:event_cmbClubePesquisaAtletaItemStateChanged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        swingFrm.setFrmPesquisaAtleta();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnLimparPesquisaAtleta;
    public static javax.swing.JButton btnPesquisaAtleta;
    public static org.bolivia.combo.SComboBoxBlue cmbClubePesquisaAtleta;
    private javax.swing.JScrollPane jScrollPanePesquisaAtleta;
    private swing.JLabelBordas lbClubePesquisaAtleta;
    private swing.JLabelBordas lbNomePesquisaAtleta;
    private swing.JLabelBordas lbTotalPesquisaAtleta;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JPanel painelPrincipal;
    public static javax.swing.JTable tabelaPesquisaAtleta;
    public static app.bolivia.swing.JCTextField txtNomePesquisaAtleta;
    public static app.bolivia.swing.JCTextField txtTotalPesquisaAtleta;
    // End of variables declaration//GEN-END:variables
}
