package view;

import business.GerenteDeTelas;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author nilton.brito
 */
public class TelaPrincipal extends javax.swing.JFrame {

    GerenteDeTelas gerenteDeTelas;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.gerenteDeTelas = new GerenteDeTelas(painelDesktop);

        btnDados.setVisible(false);
    }

    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "HH:mm:ss";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            lbHora.setText(String.format(formato.format(sistemaHora), now));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new swing.PainelBordas();
        painelBordas = new swing.PainelBordas();
        lbUsConecatado = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        btnAlunos = new javax.swing.JButton();
        btnDados = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        painelDataHora = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        btnExames = new javax.swing.JButton();
        painelDesktop = new swing.PainelDesktop();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bandampla System");
        setIconImage(Toolkit.getDefaultToolkit().getImage(TelaPrincipal.class.getResource("/imagens/principal/icon-50px.png")));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelPrincipal.setBackground(new java.awt.Color(242, 242, 242));

        painelBordas.setBackground(new java.awt.Color(153, 153, 255));
        painelBordas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsConecatado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsConecatado.setForeground(new java.awt.Color(255, 255, 255));
        lbUsConecatado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/conectado.png"))); // NOI18N
        lbUsConecatado.setText("USUÁRIO");
        lbUsConecatado.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        painelBordas.add(lbUsConecatado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario-1-64px.png"))); // NOI18N
        btnUsuarios.setMnemonic('u');
        btnUsuarios.setText("CADASTRO USUÁRIOS");
        btnUsuarios.setBorder(null);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario-2-64px.png"))); // NOI18N
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        painelBordas.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 140, 90));

        btnDesconectar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDesconectar.setForeground(new java.awt.Color(204, 0, 0));
        btnDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair.png"))); // NOI18N
        btnDesconectar.setText("DESCONECTAR...");
        btnDesconectar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        btnDesconectar.setContentAreaFilled(false);
        btnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        painelBordas.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlunos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario-1-64px.png"))); // NOI18N
        btnAlunos.setMnemonic('c');
        btnAlunos.setText("CADASTRO ATLETA");
        btnAlunos.setBorder(null);
        btnAlunos.setContentAreaFilled(false);
        btnAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlunos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario-2-64px.png"))); // NOI18N
        btnAlunos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        painelBordas.add(btnAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 90));

        btnDados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDados.setForeground(new java.awt.Color(255, 255, 255));
        btnDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/dados-1-64px.png"))); // NOI18N
        btnDados.setMnemonic('d');
        btnDados.setText("CADASTRO DE DADOS");
        btnDados.setBorder(null);
        btnDados.setContentAreaFilled(false);
        btnDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/dados-2-64px.png"))); // NOI18N
        btnDados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        painelBordas.add(btnDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, 90));

        btnConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-1-64px.png"))); // NOI18N
        btnConsulta.setMnemonic('s');
        btnConsulta.setText("CONSULTA");
        btnConsulta.setBorder(null);
        btnConsulta.setContentAreaFilled(false);
        btnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsulta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-2-64px.png"))); // NOI18N
        btnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        painelBordas.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 90));

        painelDataHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        painelDataHora.setOpaque(false);

        lbData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbData.setText("DIA -MÊS - ANO");
        lbData.setPreferredSize(new java.awt.Dimension(225, 20));

        lbHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHora.setText("HORA");
        lbHora.setPreferredSize(new java.awt.Dimension(225, 20));

        javax.swing.GroupLayout painelDataHoraLayout = new javax.swing.GroupLayout(painelDataHora);
        painelDataHora.setLayout(painelDataHoraLayout);
        painelDataHoraLayout.setHorizontalGroup(
            painelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbData, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDataHoraLayout.setVerticalGroup(
            painelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDataHoraLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelBordas.add(painelDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 190, -1));

        btnExames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExames.setForeground(new java.awt.Color(255, 255, 255));
        btnExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/certificado-1-64px.png"))); // NOI18N
        btnExames.setMnemonic('e');
        btnExames.setText("EXAMES");
        btnExames.setBorder(null);
        btnExames.setContentAreaFilled(false);
        btnExames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExames.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExames.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/certificado-2-64px.png"))); // NOI18N
        btnExames.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamesActionPerformed(evt);
            }
        });
        painelBordas.add(btnExames, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, 90));

        painelDesktop.setBackground(new Color(0,0,0,0));
        painelDesktop.setOpaque(false);
        painelDesktop.setPreferredSize(new java.awt.Dimension(1348, 567));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBordas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBordas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(painelPrincipal);

        setSize(new java.awt.Dimension(1360, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date sistemaData = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        lbData.setText(formato.format(sistemaData));

        //HORA DO SISTEMA
        Timer hr = new Timer(100, new TelaPrincipal.horas());
        hr.start();
    }//GEN-LAST:event_formWindowOpened

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        gerenteDeTelas.abrirJanelas(FrmUsuarios.getInstancia());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Deseja fechar a sessão do usuário?", "Fechar Sessão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon-question.png"))) == JOptionPane.YES_OPTION) {
            System.exit(0);
            //this.dispose();
            //TelaLogin login = new TelaLogin();
            //login.setVisible(true);
        }
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        // TODO add your handling code here:
        gerenteDeTelas.abrirJanelas(FrmAtleta.getInstancia());
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        // TODO add your handling code here:
        gerenteDeTelas.abrirJanelas(FrmDados.getInstancia());
    }//GEN-LAST:event_btnDadosActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        gerenteDeTelas.abrirJanelas(FrmPesquisa.getInstancia());
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamesActionPerformed
        // TODO add your handling code here:
        gerenteDeTelas.abrirJanelas(FrmExames.getInstancia());
    }//GEN-LAST:event_btnExamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnDados;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnExames;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHora;
    public static javax.swing.JLabel lbUsConecatado;
    private swing.PainelBordas painelBordas;
    private javax.swing.JPanel painelDataHora;
    private swing.PainelDesktop painelDesktop;
    private swing.PainelBordas painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
