package view;

import Atxy2k.CustomTextField.RestrictedTextField;
import business.AtletaBS;
import swing.SwingFrm;
import static view.FrmAtleta.*;

/**
 *
 * @author nilton.brito
 */
public class FrmAtleta extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmAtleta frmAtleta;

    // Método gerenciador de janelas abertas
    public static FrmAtleta getInstancia() {
        if (frmAtleta == null) {
            frmAtleta = new FrmAtleta();
        }
        return frmAtleta;
    }

    // Instancia da Classe 
    SwingFrm swingFrm = new SwingFrm();
    AtletaBS atletaBS = new AtletaBS();

    /**
     * Creates new form FrmAlunos
     */
    public FrmAtleta() {
        initComponents();
        RestrictedTextField validarUsuario;
        validarUsuario = new RestrictedTextField(txtNome);
        validarUsuario.setLimit(150);

        tabelaAtleta.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaAtleta.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());

        lbIdDangay.setVisible(false);
        txtIdDangay.setVisible(false);
        lbIdYudannsha.setVisible(false);
        txtIdYudannsha.setVisible(false);
        lbIdCbksc.setVisible(false);
        txtIdCbksc.setVisible(false);
        lbId.setVisible(false);
        txtId.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        painelPrincipal = new javax.swing.JPanel();
        painelRegistro = new swing.PainelBordas();
        txtIdAtleta = new app.bolivia.swing.JCTextField();
        lbIdAtleta = new swing.JLabelBordas();
        txtNome = new app.bolivia.swing.JCTextField();
        lbNome = new swing.JLabelBordas();
        cmbSexoAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbSexoAtleta = new swing.JLabelBordas();
        txtNascimento = new javax.swing.JFormattedTextField();
        lbNascimento = new swing.JLabelBordas();
        txtIdade = new app.bolivia.swing.JCTextField();
        lbIdade = new swing.JLabelBordas();
        txtCpf = new javax.swing.JFormattedTextField();
        lbCpf = new swing.JLabelBordas();
        cmbClubeAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbClubeAtleta = new swing.JLabelBordas();
        cmbFaixaAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbFaixaAtleta = new swing.JLabelBordas();
        txtDataCad = new app.bolivia.swing.JCTextField();
        lbDataCad = new swing.JLabelBordas();
        txtCategoria = new app.bolivia.swing.JCTextField();
        lbCategoria = new swing.JLabelBordas();
        txtTotalAtleta = new app.bolivia.swing.JCTextField();
        lbTotalAtleta = new swing.JLabelBordas();
        txtIdDangay = new app.bolivia.swing.JCTextField();
        lbIdDangay = new swing.JLabelBordas();
        txtIdYudannsha = new app.bolivia.swing.JCTextField();
        lbIdYudannsha = new swing.JLabelBordas();
        txtIdCbksc = new app.bolivia.swing.JCTextField();
        lbIdCbksc = new swing.JLabelBordas();
        txtId = new app.bolivia.swing.JCTextField();
        lbId = new swing.JLabelBordas();
        cmbEstadoAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbEstadoAtleta = new swing.JLabelBordas();
        painelOpcoes = new swing.PainelBordas();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnDeletarTudo = new javax.swing.JButton();
        painelPesquisar = new javax.swing.JPanel();
        txtPesquisar = new app.bolivia.swing.JCTextField();
        lbPesquisar = new swing.JLabelBordas();
        jScrollPane = new javax.swing.JScrollPane();
        tabelaAtleta = new javax.swing.JTable();
        painelTipoAtleta = new javax.swing.JPanel();
        jRadioBtnDangayAtleta = new javax.swing.JRadioButton();
        jRadioBtnYudanshaAtleta = new javax.swing.JRadioButton();
        jRadioBtnCbkscAtleta = new javax.swing.JRadioButton();

        setClosable(true);
        setForeground(java.awt.Color.black);
        setTitle("CADASTRO DE ATLETA");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1348, 623));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        painelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelRegistro.setPreferredSize(new java.awt.Dimension(1324, 205));
        painelRegistro.setRequestFocusEnabled(false);
        painelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdAtleta.setEditable(false);
        txtIdAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtIdAtleta.setBorder(null);
        txtIdAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdAtleta.setPlaceholder("ID ATLETA");
        painelRegistro.add(txtIdAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 30));

        lbIdAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbIdAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbIdAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/id-refresh.png"))); // NOI18N
        lbIdAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbIdAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 50));

        txtNome.setBackground(new java.awt.Color(34, 102, 145));
        txtNome.setBorder(null);
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNome.setPhColor(new java.awt.Color(255, 255, 255));
        txtNome.setPlaceholder("NOME USUÁRIO");
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        painelRegistro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 410, 30));

        lbNome.setBackground(new java.awt.Color(34, 102, 145));
        lbNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/user.png"))); // NOI18N
        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 480, 50));

        cmbSexoAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbSexoAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbSexoAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbSexoAtleta.setOpaque(false);
        cmbSexoAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSexoAtletaItemStateChanged(evt);
            }
        });
        painelRegistro.add(cmbSexoAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 200, -1));

        lbSexoAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbSexoAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbSexoAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbSexoAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSexoAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/sexo.png"))); // NOI18N
        lbSexoAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSexoAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbSexoAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 260, 50));

        txtNascimento.setBackground(new java.awt.Color(35, 102, 145));
        txtNascimento.setBorder(null);
        txtNascimento.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNascimentoFocusLost(evt);
            }
        });
        painelRegistro.add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 100, 30));

        lbNascimento.setBackground(new java.awt.Color(34, 102, 145));
        lbNascimento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lbNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lbNascimento.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNascimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/calendar_clock.png"))); // NOI18N
        lbNascimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNascimento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 170, 50));

        txtIdade.setEditable(false);
        txtIdade.setBackground(new java.awt.Color(34, 102, 145));
        txtIdade.setBorder(null);
        txtIdade.setForeground(new java.awt.Color(255, 255, 255));
        txtIdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdade.setToolTipText("");
        txtIdade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdade.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdade.setPlaceholder("IDADE");
        painelRegistro.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 50, 30));

        lbIdade.setBackground(new java.awt.Color(34, 102, 145));
        lbIdade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdade.setForeground(new java.awt.Color(255, 255, 255));
        lbIdade.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/idade.png"))); // NOI18N
        lbIdade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdade.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 130, 50));

        txtCpf.setBackground(new java.awt.Color(34, 102, 145));
        txtCpf.setBorder(null);
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelRegistro.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 30));

        lbCpf.setBackground(new java.awt.Color(34, 102, 145));
        lbCpf.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbCpf.setForeground(new java.awt.Color(255, 255, 255));
        lbCpf.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cpf.png"))); // NOI18N
        lbCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCpf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 50));

        cmbClubeAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbClubeAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbClubeAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbClubeAtleta.setOpaque(false);
        painelRegistro.add(cmbClubeAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 380, -1));

        lbClubeAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbClubeAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbClubeAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbClubeAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbClubeAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/clube.png"))); // NOI18N
        lbClubeAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClubeAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbClubeAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 450, 50));

        cmbFaixaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbFaixaAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbFaixaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbFaixaAtleta.setOpaque(false);
        cmbFaixaAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFaixaAtletaItemStateChanged(evt);
            }
        });
        painelRegistro.add(cmbFaixaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        lbFaixaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbFaixaAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbFaixaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbFaixaAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbFaixaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/faixa-1.png"))); // NOI18N
        lbFaixaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbFaixaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbFaixaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 50));

        txtDataCad.setEditable(false);
        txtDataCad.setBackground(new java.awt.Color(34, 102, 145));
        txtDataCad.setBorder(null);
        txtDataCad.setForeground(new java.awt.Color(255, 255, 255));
        txtDataCad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataCad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDataCad.setPhColor(new java.awt.Color(255, 255, 255));
        txtDataCad.setPlaceholder("DATA DE CADASTRO");
        painelRegistro.add(txtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 140, 30));

        lbDataCad.setBackground(new java.awt.Color(34, 102, 145));
        lbDataCad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbDataCad.setForeground(new java.awt.Color(255, 255, 255));
        lbDataCad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbDataCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/calendar_clock.png"))); // NOI18N
        lbDataCad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataCad.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 200, 50));

        txtCategoria.setEditable(false);
        txtCategoria.setBackground(new java.awt.Color(34, 102, 145));
        txtCategoria.setBorder(null);
        txtCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCategoria.setPhColor(new java.awt.Color(255, 255, 255));
        txtCategoria.setPlaceholder("CATEGORIA");
        txtCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCategoriaMouseClicked(evt);
            }
        });
        painelRegistro.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 410, 30));

        lbCategoria.setBackground(new java.awt.Color(34, 102, 145));
        lbCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/categoria.png"))); // NOI18N
        lbCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 480, 50));

        txtTotalAtleta.setEditable(false);
        txtTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtTotalAtleta.setBorder(null);
        txtTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAtleta.setToolTipText("");
        txtTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setPlaceholder("TOTAL ATLETAS");
        txtTotalAtleta.setVerifyInputWhenFocusTarget(false);
        painelRegistro.add(txtTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 110, 30));

        lbTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbTotalAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotalAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 130, 50));

        txtIdDangay.setEditable(false);
        txtIdDangay.setBackground(new java.awt.Color(34, 102, 145));
        txtIdDangay.setBorder(null);
        txtIdDangay.setForeground(new java.awt.Color(255, 255, 255));
        txtIdDangay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdDangay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdDangay.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdDangay.setPlaceholder("ID DANGAY");
        painelRegistro.add(txtIdDangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 30));

        lbIdDangay.setBackground(new java.awt.Color(34, 102, 145));
        lbIdDangay.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdDangay.setForeground(new java.awt.Color(255, 255, 255));
        lbIdDangay.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdDangay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbIdDangay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdDangay.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbIdDangay.setRequestFocusEnabled(false);
        painelRegistro.add(lbIdDangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 50));

        txtIdYudannsha.setEditable(false);
        txtIdYudannsha.setBackground(new java.awt.Color(34, 102, 145));
        txtIdYudannsha.setBorder(null);
        txtIdYudannsha.setForeground(new java.awt.Color(255, 255, 255));
        txtIdYudannsha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdYudannsha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdYudannsha.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdYudannsha.setPlaceholder("ID YUDANSHA");
        painelRegistro.add(txtIdYudannsha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, 30));

        lbIdYudannsha.setBackground(new java.awt.Color(34, 102, 145));
        lbIdYudannsha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdYudannsha.setForeground(new java.awt.Color(255, 255, 255));
        lbIdYudannsha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdYudannsha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbIdYudannsha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdYudannsha.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbIdYudannsha.setRequestFocusEnabled(false);
        painelRegistro.add(lbIdYudannsha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, 50));

        txtIdCbksc.setEditable(false);
        txtIdCbksc.setBackground(new java.awt.Color(34, 102, 145));
        txtIdCbksc.setBorder(null);
        txtIdCbksc.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCbksc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCbksc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdCbksc.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdCbksc.setPlaceholder("ID CBKSC");
        painelRegistro.add(txtIdCbksc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, 30));

        lbIdCbksc.setBackground(new java.awt.Color(34, 102, 145));
        lbIdCbksc.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdCbksc.setForeground(new java.awt.Color(255, 255, 255));
        lbIdCbksc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdCbksc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbIdCbksc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdCbksc.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbIdCbksc.setRequestFocusEnabled(false);
        painelRegistro.add(lbIdCbksc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 130, 50));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(34, 102, 145));
        txtId.setBorder(null);
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId.setPhColor(new java.awt.Color(255, 255, 255));
        txtId.setPlaceholder("ID");
        painelRegistro.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 60, 30));

        lbId.setBackground(new java.awt.Color(34, 102, 145));
        lbId.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbId.setForeground(new java.awt.Color(255, 255, 255));
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbId.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbId.setRequestFocusEnabled(false);
        painelRegistro.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 130, 50));

        cmbEstadoAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbEstadoAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbEstadoAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEstadoAtleta.setOpaque(false);
        painelRegistro.add(cmbEstadoAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, -1));

        lbEstadoAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbEstadoAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbEstadoAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbEstadoAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbEstadoAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/cep.png"))); // NOI18N
        lbEstadoAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEstadoAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbEstadoAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 270, 50));

        painelPrincipal.add(painelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 270));

        painelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(34, 102, 145))); // NOI18N
        painelOpcoes.setPreferredSize(new java.awt.Dimension(163, 180));
        painelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(34, 102, 145));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-50px.png"))); // NOI18N
        btnAdicionar.setText("CADASTRAR");
        btnAdicionar.setBorder(null);
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setContentAreaFilled(false);
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-50px.png"))); // NOI18N
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(34, 102, 145));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-50px.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setEnabled(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-50px.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(34, 102, 145));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-50px.png"))); // NOI18N
        btnDeletar.setText("APAGAR");
        btnDeletar.setBorder(null);
        btnDeletar.setBorderPainted(false);
        btnDeletar.setContentAreaFilled(false);
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setEnabled(false);
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-50px.png"))); // NOI18N
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        tabelaAtleta = new javax.swing.JTable(){
            public boolean isCellEditable(int eowIndex, int colIndex){
                return false;
            }
        };
        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(34, 102, 145));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setEnabled(false);
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btnDeletarTudo.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletarTudo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeletarTudo.setForeground(new java.awt.Color(34, 102, 145));
        btnDeletarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagarT-1-50px.png"))); // NOI18N
        btnDeletarTudo.setText("APAGAR T");
        btnDeletarTudo.setBorder(null);
        btnDeletarTudo.setBorderPainted(false);
        btnDeletarTudo.setContentAreaFilled(false);
        btnDeletarTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletarTudo.setEnabled(false);
        btnDeletarTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletarTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagarT-2-50px.png"))); // NOI18N
        btnDeletarTudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarTudoActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnDeletarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        painelPrincipal.add(painelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 330, 110));

        painelPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        painelPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(34, 102, 145))); // NOI18N
        painelPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        txtPesquisar.setBorder(null);
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPesquisar.setPhColor(new java.awt.Color(255, 255, 255));
        txtPesquisar.setPlaceholder("MATRICULA/NOME");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painelPesquisar.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 30));

        lbPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        lbPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/search2.png"))); // NOI18N
        lbPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisar.add(lbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 50));

        painelPrincipal.add(painelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 330, 80));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setAutoscrolls(true);

        tabelaAtleta = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        tabelaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaAtleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DANGAY", "ID YUDANSHA", "ID CBKSC", "NOME", "CPF", "SEXO", "NASC", "IDADE", "CLUBE", "FAIXA", "ESTADO", "CATEGORIA", "DATA_CADASTRO", "DATA_ATUALIZAÇÃO", "ID GERAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAtleta.setFocusable(false);
        tabelaAtleta.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaAtleta.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaAtleta.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaAtleta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAtleta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAtleta.getTableHeader().setReorderingAllowed(false);
        tabelaAtleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAtletaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tabelaAtleta);

        painelPrincipal.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1315, 300));

        painelTipoAtleta.setBackground(new java.awt.Color(255, 255, 255));
        painelTipoAtleta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SELECIONE TIPO DE CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelTipoAtleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioBtnDangayAtleta.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTipo.add(jRadioBtnDangayAtleta);
        jRadioBtnDangayAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnDangayAtleta.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnDangayAtleta.setSelected(true);
        jRadioBtnDangayAtleta.setText("Dangay");
        jRadioBtnDangayAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnDangayAtletaItemStateChanged(evt);
            }
        });
        painelTipoAtleta.add(jRadioBtnDangayAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jRadioBtnYudanshaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTipo.add(jRadioBtnYudanshaAtleta);
        jRadioBtnYudanshaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnYudanshaAtleta.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnYudanshaAtleta.setText("Yudansha");
        jRadioBtnYudanshaAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnYudanshaAtletaItemStateChanged(evt);
            }
        });
        painelTipoAtleta.add(jRadioBtnYudanshaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 20));

        jRadioBtnCbkscAtleta.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTipo.add(jRadioBtnCbkscAtleta);
        jRadioBtnCbkscAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnCbkscAtleta.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnCbkscAtleta.setText("CBKSC");
        jRadioBtnCbkscAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnCbkscAtletaItemStateChanged(evt);
            }
        });
        painelTipoAtleta.add(jRadioBtnCbkscAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));

        painelPrincipal.add(painelTipoAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 330, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1348, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Chamando o metodo para adicionar
        atletaBS.adicionarAtleta();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Chamando o metodo para editar
        atletaBS.editarAtleta();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // Chamando o metodo para deletar
        atletaBS.deletarAtleta();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Chamando o metodo para limpar os campos
        atletaBS.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        txtNome.setText(txtNome.getText().toUpperCase());
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_txtNomeKeyReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // Chamando o metodo para popular ComboBox e gerar ID
        atletaBS.gerarId();
        swingFrm.setComboBoxFrmAtleta();
        swingFrm.setCmbFaixaAtleta();
    }//GEN-LAST:event_formInternalFrameActivated

    private void tabelaAtletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAtletaMouseClicked
        // Chamando o metodo para setar a categoria do atleta
        atletaBS.setarCampos();
        atletaBS.setarTipoCadastro();
    }//GEN-LAST:event_tabelaAtletaMouseClicked

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // Chamando o metodo pesquisar clientes
        txtPesquisar.setText(txtPesquisar.getText().toUpperCase());
        atletaBS.pesquisarAtleta();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void jRadioBtnYudanshaAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnYudanshaAtletaItemStateChanged
        // Chamando o metodo para popular ComboBox e gerar ID
        swingFrm.setCmbFaixaAtleta();
        atletaBS.gerarId();
    }//GEN-LAST:event_jRadioBtnYudanshaAtletaItemStateChanged

    private void jRadioBtnDangayAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnDangayAtletaItemStateChanged
        // Chamando o metodo para popular ComboBox e gerar ID
        swingFrm.setCmbFaixaAtleta();
        atletaBS.gerarId();
    }//GEN-LAST:event_jRadioBtnDangayAtletaItemStateChanged

    private void txtNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascimentoFocusLost
        // Chamando o metodo para calcular a idade do atleta
        atletaBS.calcularIdade();
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_txtNascimentoFocusLost

    private void cmbFaixaAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFaixaAtletaItemStateChanged
        // Chamando o metodo para setar a categoria do atleta
        atletaBS.setarCategoria();
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_cmbFaixaAtletaItemStateChanged

    private void cmbSexoAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSexoAtletaItemStateChanged
        // Chamando o metodo para setar a categoria do atleta
        atletaBS.setarCategoria();
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_cmbSexoAtletaItemStateChanged

    private void txtCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCategoriaMouseClicked
        // Chamando o metodo para setar a categoria do atleta
        atletaBS.setarCategoria();
    }//GEN-LAST:event_txtCategoriaMouseClicked

    private void jRadioBtnCbkscAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnCbkscAtletaItemStateChanged
        // Chamando o metodo para popular ComboBox e gerar ID
        swingFrm.setCmbFaixaAtleta();
        atletaBS.gerarId();
    }//GEN-LAST:event_jRadioBtnCbkscAtletaItemStateChanged

    private void btnDeletarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarTudoActionPerformed
        // Chamando o metodo para deletar todos os atletas
        atletaBS.deletarTodosAtletas();
    }//GEN-LAST:event_btnDeletarTudoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnDeletarTudo;
    public static javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup btnGroupTipo;
    public static javax.swing.JButton btnLimpar;
    public static org.bolivia.combo.SComboBoxBlue cmbClubeAtleta;
    public static org.bolivia.combo.SComboBoxBlue cmbEstadoAtleta;
    public static org.bolivia.combo.SComboBoxBlue cmbFaixaAtleta;
    public static org.bolivia.combo.SComboBoxBlue cmbSexoAtleta;
    public static javax.swing.JRadioButton jRadioBtnCbkscAtleta;
    public static javax.swing.JRadioButton jRadioBtnDangayAtleta;
    public static javax.swing.JRadioButton jRadioBtnYudanshaAtleta;
    private javax.swing.JScrollPane jScrollPane;
    public static swing.JLabelBordas lbCategoria;
    public static swing.JLabelBordas lbClubeAtleta;
    private swing.JLabelBordas lbCpf;
    public static swing.JLabelBordas lbDataCad;
    public static swing.JLabelBordas lbEstadoAtleta;
    public static swing.JLabelBordas lbFaixaAtleta;
    public static swing.JLabelBordas lbId;
    public static swing.JLabelBordas lbIdAtleta;
    public static swing.JLabelBordas lbIdCbksc;
    public static swing.JLabelBordas lbIdDangay;
    public static swing.JLabelBordas lbIdYudannsha;
    public static swing.JLabelBordas lbIdade;
    public static swing.JLabelBordas lbNascimento;
    public static swing.JLabelBordas lbNome;
    public static swing.JLabelBordas lbPesquisar;
    public static swing.JLabelBordas lbSexoAtleta;
    private swing.JLabelBordas lbTotalAtleta;
    private swing.PainelBordas painelOpcoes;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JPanel painelPrincipal;
    private swing.PainelBordas painelRegistro;
    public static javax.swing.JPanel painelTipoAtleta;
    public static javax.swing.JTable tabelaAtleta;
    public static app.bolivia.swing.JCTextField txtCategoria;
    public static javax.swing.JFormattedTextField txtCpf;
    public static app.bolivia.swing.JCTextField txtDataCad;
    public static app.bolivia.swing.JCTextField txtId;
    public static app.bolivia.swing.JCTextField txtIdAtleta;
    public static app.bolivia.swing.JCTextField txtIdCbksc;
    public static app.bolivia.swing.JCTextField txtIdDangay;
    public static app.bolivia.swing.JCTextField txtIdYudannsha;
    public static app.bolivia.swing.JCTextField txtIdade;
    public static javax.swing.JFormattedTextField txtNascimento;
    public static app.bolivia.swing.JCTextField txtNome;
    public static app.bolivia.swing.JCTextField txtPesquisar;
    public static app.bolivia.swing.JCTextField txtTotalAtleta;
    // End of variables declaration//GEN-END:variables
}
