package view;

import Atxy2k.CustomTextField.RestrictedTextField;
import business.DadosBS;

/**
 *
 * @author nilto
 */
public class FrmDados extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmDados frmDados;

    // Método gerenciador de janelas abertas
    public static FrmDados getInstancia() {
        if (frmDados == null) {
            frmDados = new FrmDados();
        }
        return frmDados;
    }

    DadosBS dadosBS = new DadosBS();

    /**
     * Creates new form FrmDados
     */
    public FrmDados() {
        initComponents();

        RestrictedTextField validarCategoria = new RestrictedTextField(txtNomeCategoria);
        validarCategoria.setLimit(60);
        RestrictedTextField validarIdCategoria = new RestrictedTextField(txtIdCategoria);
        //validar.setOnlyNums(true);
        validarIdCategoria.setLimit(4);

        tabelaCategoria.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaCategoria.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());
        tabelaParametro.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaParametro.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());
        tabelaFaixa.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaFaixa.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelCategoria = new javax.swing.JPanel();
        txtIdCategoria = new app.bolivia.swing.JCTextField();
        lbIdCategoria = new swing.JLabelBordas();
        txtNomeCategoria = new app.bolivia.swing.JCTextField();
        lbCategoria = new swing.JLabelBordas();
        jScrollPaneCategoria = new javax.swing.JScrollPane();
        tabelaCategoria = new javax.swing.JTable();
        painelBotoes1 = new javax.swing.JPanel();
        btnAdinionarCategoria = new javax.swing.JButton();
        btnEditarCategoria = new javax.swing.JButton();
        btnLimparCategoria = new javax.swing.JButton();
        btnApagarCategoria = new javax.swing.JButton();
        painelParametroCategoria = new javax.swing.JPanel();
        txtIdParametro = new app.bolivia.swing.JCTextField();
        lbIdParametro = new swing.JLabelBordas();
        txtNomeParametro = new app.bolivia.swing.JCTextField();
        lbNomeParametro = new swing.JLabelBordas();
        txtIdadeMinParametro = new app.bolivia.swing.JCTextField();
        lbIdadeMinParametro = new swing.JLabelBordas();
        txtIdadeMaxParametro = new app.bolivia.swing.JCTextField();
        lbIdadeMaxParametro = new swing.JLabelBordas();
        txtIdMinParametro = new app.bolivia.swing.JCTextField();
        lbIdMinParametro = new swing.JLabelBordas();
        txtIdMaxParametro = new app.bolivia.swing.JCTextField();
        lbIdMaxParametro = new swing.JLabelBordas();
        txtSexoParametro = new app.bolivia.swing.JCTextField();
        lbSexoParametro = new swing.JLabelBordas();
        jScrollPaneParametro = new javax.swing.JScrollPane();
        tabelaParametro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnLimparParametro = new javax.swing.JButton();
        btnApagarParametro = new javax.swing.JButton();
        btnEditarParametro = new javax.swing.JButton();
        btnAdicionarParametro = new javax.swing.JButton();
        painelFaixa = new javax.swing.JPanel();
        txtIdFaixa = new app.bolivia.swing.JCTextField();
        lbIdFaixa = new swing.JLabelBordas();
        txtNomeFaixa = new app.bolivia.swing.JCTextField();
        lbIdFaixa1 = new swing.JLabelBordas();
        txtGrauFaixa = new app.bolivia.swing.JCTextField();
        lbIdFaixa2 = new swing.JLabelBordas();
        txtMenorIdadeFaixa = new app.bolivia.swing.JCTextField();
        lbIdFaixa3 = new swing.JLabelBordas();
        txtMaiorIdadeFaixa = new app.bolivia.swing.JCTextField();
        lbIdFaixa4 = new swing.JLabelBordas();
        jScrollPaneFaixa = new javax.swing.JScrollPane();
        tabelaFaixa = new javax.swing.JTable();
        painelBotoes2 = new javax.swing.JPanel();
        btnLimparFaixa = new javax.swing.JButton();
        btnApagarFaixa = new javax.swing.JButton();
        btnEditarFaixa = new javax.swing.JButton();
        btnAdicionarFaixa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 0));
        setTitle("CADASTRO DE DADOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1348, 623));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        painelCategoria.setBackground(new java.awt.Color(255, 255, 255));
        painelCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRO CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelCategoria.setPreferredSize(new java.awt.Dimension(330, 520));
        painelCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdCategoria.setBackground(new java.awt.Color(34, 102, 145));
        txtIdCategoria.setBorder(null);
        txtIdCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdCategoria.setToolTipText("");
        txtIdCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdCategoria.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdCategoria.setPlaceholder("ID");
        txtIdCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdCategoriaKeyReleased(evt);
            }
        });
        painelCategoria.add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 30));

        lbIdCategoria.setBackground(new java.awt.Color(34, 102, 145));
        lbIdCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbIdCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCategoria.add(lbIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 50));

        txtNomeCategoria.setBackground(new java.awt.Color(34, 102, 145));
        txtNomeCategoria.setBorder(null);
        txtNomeCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeCategoria.setToolTipText("");
        txtNomeCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeCategoria.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomeCategoria.setPlaceholder("CATEGORIA");
        txtNomeCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeCategoriaKeyReleased(evt);
            }
        });
        painelCategoria.add(txtNomeCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 370, 30));

        lbCategoria.setBackground(new java.awt.Color(34, 102, 145));
        lbCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCategoria.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 390, 50));

        jScrollPaneCategoria.setPreferredSize(new java.awt.Dimension(500, 161));

        tabelaCategoria = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaCategoria.setBackground(new java.awt.Color(255, 255, 255));
        tabelaCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaCategoria.setForeground(new java.awt.Color(35, 102, 145));
        tabelaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCategoria.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaCategoria.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaCategoria.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaCategoria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCategoria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCategoria.getTableHeader().setReorderingAllowed(false);
        tabelaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCategoriaMouseClicked(evt);
            }
        });
        jScrollPaneCategoria.setViewportView(tabelaCategoria);

        painelCategoria.add(jScrollPaneCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 500, 130));

        painelBotoes1.setOpaque(false);
        painelBotoes1.setLayout(new java.awt.GridLayout());

        btnAdinionarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btnAdinionarCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdinionarCategoria.setForeground(new java.awt.Color(35, 102, 145));
        btnAdinionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-50px.png"))); // NOI18N
        btnAdinionarCategoria.setText("ADICIONAR");
        btnAdinionarCategoria.setBorder(null);
        btnAdinionarCategoria.setBorderPainted(false);
        btnAdinionarCategoria.setContentAreaFilled(false);
        btnAdinionarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdinionarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdinionarCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-50px.png"))); // NOI18N
        btnAdinionarCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdinionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdinionarCategoriaActionPerformed(evt);
            }
        });
        painelBotoes1.add(btnAdinionarCategoria);

        btnEditarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarCategoria.setForeground(new java.awt.Color(35, 102, 145));
        btnEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-50px.png"))); // NOI18N
        btnEditarCategoria.setText("EDITAR");
        btnEditarCategoria.setBorder(null);
        btnEditarCategoria.setBorderPainted(false);
        btnEditarCategoria.setContentAreaFilled(false);
        btnEditarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCategoria.setEnabled(false);
        btnEditarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-50px.png"))); // NOI18N
        btnEditarCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCategoriaActionPerformed(evt);
            }
        });
        painelBotoes1.add(btnEditarCategoria);

        btnLimparCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparCategoria.setForeground(new java.awt.Color(35, 102, 145));
        btnLimparCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimparCategoria.setText("LIMPAR");
        btnLimparCategoria.setBorder(null);
        btnLimparCategoria.setBorderPainted(false);
        btnLimparCategoria.setContentAreaFilled(false);
        btnLimparCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCategoria.setEnabled(false);
        btnLimparCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimparCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCategoriaActionPerformed(evt);
            }
        });
        painelBotoes1.add(btnLimparCategoria);

        btnApagarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        btnApagarCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApagarCategoria.setForeground(new java.awt.Color(35, 102, 145));
        btnApagarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-50px.png"))); // NOI18N
        btnApagarCategoria.setText("APAGAR");
        btnApagarCategoria.setBorder(null);
        btnApagarCategoria.setBorderPainted(false);
        btnApagarCategoria.setContentAreaFilled(false);
        btnApagarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarCategoria.setEnabled(false);
        btnApagarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagarCategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-50px.png"))); // NOI18N
        btnApagarCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApagarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarCategoriaActionPerformed(evt);
            }
        });
        painelBotoes1.add(btnApagarCategoria);

        painelCategoria.add(painelBotoes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 72));

        painelParametroCategoria.setBackground(new java.awt.Color(255, 255, 255));
        painelParametroCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRO PARÂMENTROS CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelParametroCategoria.setPreferredSize(new java.awt.Dimension(795, 330));
        painelParametroCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtIdParametro.setBorder(null);
        txtIdParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdParametro.setToolTipText("");
        txtIdParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdParametro.setPlaceholder("Nº");
        txtIdParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtIdParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 30));

        lbIdParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbIdParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbIdParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        txtNomeParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtNomeParametro.setBorder(null);
        txtNomeParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeParametro.setToolTipText("");
        txtNomeParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomeParametro.setPlaceholder("PARÂMETRO DA CATEGORIA");
        txtNomeParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtNomeParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, 30));

        lbNomeParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbNomeParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbNomeParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNomeParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomeParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbNomeParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 230, 50));

        txtIdadeMinParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtIdadeMinParametro.setBorder(null);
        txtIdadeMinParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdadeMinParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdadeMinParametro.setToolTipText("");
        txtIdadeMinParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdadeMinParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdadeMinParametro.setPlaceholder("IDADE MIN");
        txtIdadeMinParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdadeMinParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtIdadeMinParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 80, 30));

        lbIdadeMinParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbIdadeMinParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdadeMinParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdadeMinParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdadeMinParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdadeMinParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbIdadeMinParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, 50));

        txtIdadeMaxParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtIdadeMaxParametro.setBorder(null);
        txtIdadeMaxParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdadeMaxParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdadeMaxParametro.setToolTipText("");
        txtIdadeMaxParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdadeMaxParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdadeMaxParametro.setPlaceholder("IDADE MAX");
        txtIdadeMaxParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdadeMaxParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtIdadeMaxParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 80, 30));

        lbIdadeMaxParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbIdadeMaxParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdadeMaxParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdadeMaxParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdadeMaxParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdadeMaxParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbIdadeMaxParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 50));

        txtIdMinParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtIdMinParametro.setBorder(null);
        txtIdMinParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdMinParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdMinParametro.setToolTipText("");
        txtIdMinParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdMinParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdMinParametro.setPlaceholder("ID MIN FAIXA");
        txtIdMinParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdMinParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtIdMinParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 90, 30));

        lbIdMinParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbIdMinParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdMinParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdMinParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdMinParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdMinParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbIdMinParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 50));

        txtIdMaxParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtIdMaxParametro.setBorder(null);
        txtIdMaxParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdMaxParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdMaxParametro.setToolTipText("");
        txtIdMaxParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdMaxParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdMaxParametro.setPlaceholder("ID MAX FAIXA");
        txtIdMaxParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdMaxParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtIdMaxParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 100, 30));

        lbIdMaxParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbIdMaxParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdMaxParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdMaxParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdMaxParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdMaxParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbIdMaxParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, 50));

        txtSexoParametro.setBackground(new java.awt.Color(34, 102, 145));
        txtSexoParametro.setBorder(null);
        txtSexoParametro.setForeground(new java.awt.Color(255, 255, 255));
        txtSexoParametro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSexoParametro.setToolTipText("");
        txtSexoParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSexoParametro.setPhColor(new java.awt.Color(255, 255, 255));
        txtSexoParametro.setPlaceholder("SEXO");
        txtSexoParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSexoParametroKeyReleased(evt);
            }
        });
        painelParametroCategoria.add(txtSexoParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 210, 30));

        lbSexoParametro.setBackground(new java.awt.Color(34, 102, 145));
        lbSexoParametro.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbSexoParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbSexoParametro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSexoParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSexoParametro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelParametroCategoria.add(lbSexoParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 230, 50));

        tabelaParametro = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaParametro.setBackground(new java.awt.Color(255, 255, 255));
        tabelaParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaParametro.setForeground(new java.awt.Color(35, 102, 145));
        tabelaParametro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "PARÂMETRO CATEGORIA", "IDADE MIN", "IDADE MAX", "ID MIN FAIXA", "ID MAX FAIXA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaParametro.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaParametro.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaParametro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaParametro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaParametro.getTableHeader().setReorderingAllowed(false);
        tabelaParametro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaParametroMouseClicked(evt);
            }
        });
        jScrollPaneParametro.setViewportView(tabelaParametro);

        painelParametroCategoria.add(jScrollPaneParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 164));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout());

        btnLimparParametro.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparParametro.setForeground(new java.awt.Color(35, 102, 145));
        btnLimparParametro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimparParametro.setText("LIMPAR");
        btnLimparParametro.setBorder(null);
        btnLimparParametro.setBorderPainted(false);
        btnLimparParametro.setContentAreaFilled(false);
        btnLimparParametro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparParametro.setEnabled(false);
        btnLimparParametro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparParametro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimparParametro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparParametroActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparParametro);

        btnApagarParametro.setBackground(new java.awt.Color(255, 255, 255));
        btnApagarParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApagarParametro.setForeground(new java.awt.Color(35, 102, 145));
        btnApagarParametro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-50px.png"))); // NOI18N
        btnApagarParametro.setText("APAGAR");
        btnApagarParametro.setBorder(null);
        btnApagarParametro.setBorderPainted(false);
        btnApagarParametro.setContentAreaFilled(false);
        btnApagarParametro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarParametro.setEnabled(false);
        btnApagarParametro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagarParametro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-50px.png"))); // NOI18N
        btnApagarParametro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApagarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarParametroActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarParametro);

        btnEditarParametro.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarParametro.setForeground(new java.awt.Color(35, 102, 145));
        btnEditarParametro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-50px.png"))); // NOI18N
        btnEditarParametro.setText("EDITAR");
        btnEditarParametro.setBorder(null);
        btnEditarParametro.setBorderPainted(false);
        btnEditarParametro.setContentAreaFilled(false);
        btnEditarParametro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarParametro.setEnabled(false);
        btnEditarParametro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarParametro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-50px.png"))); // NOI18N
        btnEditarParametro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarParametroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarParametro);

        btnAdicionarParametro.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarParametro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionarParametro.setForeground(new java.awt.Color(35, 102, 145));
        btnAdicionarParametro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-50px.png"))); // NOI18N
        btnAdicionarParametro.setText("ADICIONAR");
        btnAdicionarParametro.setBorder(null);
        btnAdicionarParametro.setBorderPainted(false);
        btnAdicionarParametro.setContentAreaFilled(false);
        btnAdicionarParametro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarParametro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarParametro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-50px.png"))); // NOI18N
        btnAdicionarParametro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarParametroActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarParametro);

        painelParametroCategoria.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, 80));

        painelFaixa.setBackground(new java.awt.Color(255, 255, 255));
        painelFaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRO DE FAIXA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelFaixa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdFaixa.setBackground(new java.awt.Color(34, 102, 145));
        txtIdFaixa.setBorder(null);
        txtIdFaixa.setForeground(new java.awt.Color(255, 255, 255));
        txtIdFaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdFaixa.setToolTipText("");
        txtIdFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdFaixa.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdFaixa.setPlaceholder("ID");
        txtIdFaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdFaixaKeyReleased(evt);
            }
        });
        painelFaixa.add(txtIdFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 30));

        lbIdFaixa.setBackground(new java.awt.Color(34, 102, 145));
        lbIdFaixa.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdFaixa.setForeground(new java.awt.Color(255, 255, 255));
        lbIdFaixa.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdFaixa.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelFaixa.add(lbIdFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 50));

        txtNomeFaixa.setBackground(new java.awt.Color(34, 102, 145));
        txtNomeFaixa.setBorder(null);
        txtNomeFaixa.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeFaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeFaixa.setToolTipText("");
        txtNomeFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeFaixa.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomeFaixa.setPlaceholder("FAIXA");
        txtNomeFaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFaixaKeyReleased(evt);
            }
        });
        painelFaixa.add(txtNomeFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, 30));

        lbIdFaixa1.setBackground(new java.awt.Color(34, 102, 145));
        lbIdFaixa1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdFaixa1.setForeground(new java.awt.Color(255, 255, 255));
        lbIdFaixa1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdFaixa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdFaixa1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelFaixa.add(lbIdFaixa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 50));

        txtGrauFaixa.setBackground(new java.awt.Color(34, 102, 145));
        txtGrauFaixa.setBorder(null);
        txtGrauFaixa.setForeground(new java.awt.Color(255, 255, 255));
        txtGrauFaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrauFaixa.setToolTipText("");
        txtGrauFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGrauFaixa.setPhColor(new java.awt.Color(255, 255, 255));
        txtGrauFaixa.setPlaceholder("10º DAN");
        txtGrauFaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrauFaixaKeyReleased(evt);
            }
        });
        painelFaixa.add(txtGrauFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 30));

        lbIdFaixa2.setBackground(new java.awt.Color(34, 102, 145));
        lbIdFaixa2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdFaixa2.setForeground(new java.awt.Color(255, 255, 255));
        lbIdFaixa2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdFaixa2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdFaixa2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelFaixa.add(lbIdFaixa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 50));

        txtMenorIdadeFaixa.setBackground(new java.awt.Color(34, 102, 145));
        txtMenorIdadeFaixa.setBorder(null);
        txtMenorIdadeFaixa.setForeground(new java.awt.Color(255, 255, 255));
        txtMenorIdadeFaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMenorIdadeFaixa.setToolTipText("");
        txtMenorIdadeFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMenorIdadeFaixa.setPhColor(new java.awt.Color(255, 255, 255));
        txtMenorIdadeFaixa.setPlaceholder("MENOR 16");
        txtMenorIdadeFaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMenorIdadeFaixaKeyReleased(evt);
            }
        });
        painelFaixa.add(txtMenorIdadeFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, 30));

        lbIdFaixa3.setBackground(new java.awt.Color(34, 102, 145));
        lbIdFaixa3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdFaixa3.setForeground(new java.awt.Color(255, 255, 255));
        lbIdFaixa3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdFaixa3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdFaixa3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelFaixa.add(lbIdFaixa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, 50));

        txtMaiorIdadeFaixa.setBackground(new java.awt.Color(34, 102, 145));
        txtMaiorIdadeFaixa.setBorder(null);
        txtMaiorIdadeFaixa.setForeground(new java.awt.Color(255, 255, 255));
        txtMaiorIdadeFaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaiorIdadeFaixa.setToolTipText("");
        txtMaiorIdadeFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMaiorIdadeFaixa.setPhColor(new java.awt.Color(255, 255, 255));
        txtMaiorIdadeFaixa.setPlaceholder("MAIOR 16");
        txtMaiorIdadeFaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaiorIdadeFaixaKeyReleased(evt);
            }
        });
        painelFaixa.add(txtMaiorIdadeFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 30));

        lbIdFaixa4.setBackground(new java.awt.Color(34, 102, 145));
        lbIdFaixa4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdFaixa4.setForeground(new java.awt.Color(255, 255, 255));
        lbIdFaixa4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdFaixa4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdFaixa4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelFaixa.add(lbIdFaixa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, 50));

        tabelaFaixa = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaFaixa.setBackground(new java.awt.Color(255, 255, 255));
        tabelaFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaFaixa.setForeground(new java.awt.Color(35, 102, 145));
        tabelaFaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FAIXA", "GRAU", "MENOR 16 ANOS", "MAIOR 16 ANOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFaixa.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaFaixa.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaFaixa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaFaixa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaFaixa.getTableHeader().setReorderingAllowed(false);
        tabelaFaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFaixaMouseClicked(evt);
            }
        });
        jScrollPaneFaixa.setViewportView(tabelaFaixa);

        painelFaixa.add(jScrollPaneFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 500, 130));

        painelBotoes2.setOpaque(false);
        painelBotoes2.setLayout(new java.awt.GridLayout());

        btnLimparFaixa.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparFaixa.setForeground(new java.awt.Color(35, 102, 145));
        btnLimparFaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimparFaixa.setText("LIMPAR");
        btnLimparFaixa.setBorder(null);
        btnLimparFaixa.setBorderPainted(false);
        btnLimparFaixa.setContentAreaFilled(false);
        btnLimparFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparFaixa.setEnabled(false);
        btnLimparFaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimparFaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFaixaActionPerformed(evt);
            }
        });
        painelBotoes2.add(btnLimparFaixa);

        btnApagarFaixa.setBackground(new java.awt.Color(255, 255, 255));
        btnApagarFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApagarFaixa.setForeground(new java.awt.Color(35, 102, 145));
        btnApagarFaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-50px.png"))); // NOI18N
        btnApagarFaixa.setText("APAGAR");
        btnApagarFaixa.setBorder(null);
        btnApagarFaixa.setBorderPainted(false);
        btnApagarFaixa.setContentAreaFilled(false);
        btnApagarFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarFaixa.setEnabled(false);
        btnApagarFaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagarFaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-50px.png"))); // NOI18N
        btnApagarFaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApagarFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarFaixaActionPerformed(evt);
            }
        });
        painelBotoes2.add(btnApagarFaixa);

        btnEditarFaixa.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarFaixa.setForeground(new java.awt.Color(35, 102, 145));
        btnEditarFaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-50px.png"))); // NOI18N
        btnEditarFaixa.setText("EDITAR");
        btnEditarFaixa.setBorder(null);
        btnEditarFaixa.setBorderPainted(false);
        btnEditarFaixa.setContentAreaFilled(false);
        btnEditarFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarFaixa.setEnabled(false);
        btnEditarFaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarFaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-50px.png"))); // NOI18N
        btnEditarFaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFaixaActionPerformed(evt);
            }
        });
        painelBotoes2.add(btnEditarFaixa);

        btnAdicionarFaixa.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarFaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionarFaixa.setForeground(new java.awt.Color(35, 102, 145));
        btnAdicionarFaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-50px.png"))); // NOI18N
        btnAdicionarFaixa.setText("ADICIONAR");
        btnAdicionarFaixa.setBorder(null);
        btnAdicionarFaixa.setBorderPainted(false);
        btnAdicionarFaixa.setContentAreaFilled(false);
        btnAdicionarFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarFaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarFaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-50px.png"))); // NOI18N
        btnAdicionarFaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFaixaActionPerformed(evt);
            }
        });
        painelBotoes2.add(btnAdicionarFaixa);

        painelFaixa.add(painelBotoes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 500, 80));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelParametroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                        .addComponent(painelParametroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                        .addComponent(painelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(painelFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1349, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdinionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdinionarCategoriaActionPerformed
        dadosBS.adicionarCategoria();
        dadosBS.pesquisarCategoria();
    }//GEN-LAST:event_btnAdinionarCategoriaActionPerformed

    private void btnEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCategoriaActionPerformed
        dadosBS.editarCategoria();
        dadosBS.pesquisarCategoria();
    }//GEN-LAST:event_btnEditarCategoriaActionPerformed

    private void btnApagarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarCategoriaActionPerformed
        dadosBS.deletarCategoria();
        dadosBS.pesquisarCategoria();
    }//GEN-LAST:event_btnApagarCategoriaActionPerformed

    private void btnLimparCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCategoriaActionPerformed
        dadosBS.limparCampos();
        dadosBS.pesquisarCategoria();
    }//GEN-LAST:event_btnLimparCategoriaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        dadosBS.pesquisarCategoria();
        dadosBS.pesquisarParametro();
        dadosBS.pesquisarFaixa();
    }//GEN-LAST:event_formInternalFrameActivated

    private void tabelaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCategoriaMouseClicked
        // TODO add your handling code here:
        dadosBS.setarCampos();
    }//GEN-LAST:event_tabelaCategoriaMouseClicked

    private void btnAdicionarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarParametroActionPerformed
        dadosBS.adicionarParametro();
        dadosBS.pesquisarParametro();
    }//GEN-LAST:event_btnAdicionarParametroActionPerformed

    private void btnEditarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarParametroActionPerformed
        dadosBS.editarParametro();
        dadosBS.pesquisarParametro();
    }//GEN-LAST:event_btnEditarParametroActionPerformed

    private void btnApagarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarParametroActionPerformed
        dadosBS.deletarParametro();
        dadosBS.pesquisarParametro();
    }//GEN-LAST:event_btnApagarParametroActionPerformed

    private void btnLimparParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparParametroActionPerformed
        dadosBS.limparParametro();
        dadosBS.pesquisarParametro();
    }//GEN-LAST:event_btnLimparParametroActionPerformed

    private void tabelaParametroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaParametroMouseClicked
        dadosBS.setarParametro();
    }//GEN-LAST:event_tabelaParametroMouseClicked

    private void txtNomeCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCategoriaKeyReleased
        txtNomeCategoria.setText(txtNomeCategoria.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeCategoriaKeyReleased

    private void txtIdCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCategoriaKeyReleased
        txtIdCategoria.setText(txtIdCategoria.getText().toUpperCase());
    }//GEN-LAST:event_txtIdCategoriaKeyReleased

    private void txtNomeParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeParametroKeyReleased
        txtNomeParametro.setText(txtNomeParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeParametroKeyReleased

    private void txtIdadeMinParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdadeMinParametroKeyReleased
        txtIdadeMinParametro.setText(txtIdadeMinParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtIdadeMinParametroKeyReleased

    private void txtIdadeMaxParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdadeMaxParametroKeyReleased
        txtNomeCategoria.setText(txtNomeCategoria.getText().toUpperCase());
    }//GEN-LAST:event_txtIdadeMaxParametroKeyReleased

    private void txtIdMinParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMinParametroKeyReleased
        txtIdMinParametro.setText(txtIdMinParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtIdMinParametroKeyReleased

    private void txtIdMaxParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMaxParametroKeyReleased
        txtIdMaxParametro.setText(txtIdMaxParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtIdMaxParametroKeyReleased

    private void txtSexoParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSexoParametroKeyReleased
        txtSexoParametro.setText(txtSexoParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtSexoParametroKeyReleased

    private void txtIdParametroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdParametroKeyReleased
        txtIdParametro.setText(txtIdParametro.getText().toUpperCase());
    }//GEN-LAST:event_txtIdParametroKeyReleased

    private void txtIdFaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFaixaKeyReleased
        txtIdFaixa.setText(txtIdFaixa.getText().toUpperCase());
    }//GEN-LAST:event_txtIdFaixaKeyReleased

    private void txtNomeFaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFaixaKeyReleased
        txtNomeFaixa.setText(txtNomeFaixa.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeFaixaKeyReleased

    private void txtGrauFaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrauFaixaKeyReleased
        txtGrauFaixa.setText(txtGrauFaixa.getText().toUpperCase());
    }//GEN-LAST:event_txtGrauFaixaKeyReleased

    private void txtMenorIdadeFaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenorIdadeFaixaKeyReleased
        txtMenorIdadeFaixa.setText(txtMenorIdadeFaixa.getText().toUpperCase());
    }//GEN-LAST:event_txtMenorIdadeFaixaKeyReleased

    private void txtMaiorIdadeFaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaiorIdadeFaixaKeyReleased
        txtMaiorIdadeFaixa.setText(txtMaiorIdadeFaixa.getText().toUpperCase());
    }//GEN-LAST:event_txtMaiorIdadeFaixaKeyReleased

    private void btnAdicionarFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFaixaActionPerformed
        dadosBS.adicionarFaixa();
        dadosBS.pesquisarFaixa();
    }//GEN-LAST:event_btnAdicionarFaixaActionPerformed

    private void btnEditarFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFaixaActionPerformed
        dadosBS.editarFaixa();
        dadosBS.pesquisarFaixa();
    }//GEN-LAST:event_btnEditarFaixaActionPerformed

    private void btnApagarFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarFaixaActionPerformed
        dadosBS.deletarFaixa();
        dadosBS.pesquisarFaixa();
    }//GEN-LAST:event_btnApagarFaixaActionPerformed

    private void btnLimparFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFaixaActionPerformed
        dadosBS.limparFaixa();
        dadosBS.pesquisarFaixa();
    }//GEN-LAST:event_btnLimparFaixaActionPerformed

    private void tabelaFaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFaixaMouseClicked
        dadosBS.setarFaixa();
    }//GEN-LAST:event_tabelaFaixaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionarFaixa;
    public static javax.swing.JButton btnAdicionarParametro;
    public static javax.swing.JButton btnAdinionarCategoria;
    public static javax.swing.JButton btnApagarCategoria;
    public static javax.swing.JButton btnApagarFaixa;
    public static javax.swing.JButton btnApagarParametro;
    public static javax.swing.JButton btnEditarCategoria;
    public static javax.swing.JButton btnEditarFaixa;
    public static javax.swing.JButton btnEditarParametro;
    public static javax.swing.JButton btnLimparCategoria;
    public static javax.swing.JButton btnLimparFaixa;
    public static javax.swing.JButton btnLimparParametro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneCategoria;
    private javax.swing.JScrollPane jScrollPaneFaixa;
    private javax.swing.JScrollPane jScrollPaneParametro;
    private swing.JLabelBordas lbCategoria;
    private swing.JLabelBordas lbIdCategoria;
    private swing.JLabelBordas lbIdFaixa;
    private swing.JLabelBordas lbIdFaixa1;
    private swing.JLabelBordas lbIdFaixa2;
    private swing.JLabelBordas lbIdFaixa3;
    private swing.JLabelBordas lbIdFaixa4;
    private swing.JLabelBordas lbIdMaxParametro;
    private swing.JLabelBordas lbIdMinParametro;
    private swing.JLabelBordas lbIdParametro;
    private swing.JLabelBordas lbIdadeMaxParametro;
    private swing.JLabelBordas lbIdadeMinParametro;
    private swing.JLabelBordas lbNomeParametro;
    private swing.JLabelBordas lbSexoParametro;
    private javax.swing.JPanel painelBotoes1;
    private javax.swing.JPanel painelBotoes2;
    private javax.swing.JPanel painelCategoria;
    private javax.swing.JPanel painelFaixa;
    private javax.swing.JPanel painelParametroCategoria;
    private javax.swing.JPanel painelPrincipal;
    public static javax.swing.JTable tabelaCategoria;
    public static javax.swing.JTable tabelaFaixa;
    public static javax.swing.JTable tabelaParametro;
    public static app.bolivia.swing.JCTextField txtGrauFaixa;
    public static app.bolivia.swing.JCTextField txtIdCategoria;
    public static app.bolivia.swing.JCTextField txtIdFaixa;
    public static app.bolivia.swing.JCTextField txtIdMaxParametro;
    public static app.bolivia.swing.JCTextField txtIdMinParametro;
    public static app.bolivia.swing.JCTextField txtIdParametro;
    public static app.bolivia.swing.JCTextField txtIdadeMaxParametro;
    public static app.bolivia.swing.JCTextField txtIdadeMinParametro;
    public static app.bolivia.swing.JCTextField txtMaiorIdadeFaixa;
    public static app.bolivia.swing.JCTextField txtMenorIdadeFaixa;
    public static app.bolivia.swing.JCTextField txtNomeCategoria;
    public static app.bolivia.swing.JCTextField txtNomeFaixa;
    public static app.bolivia.swing.JCTextField txtNomeParametro;
    public static app.bolivia.swing.JCTextField txtSexoParametro;
    // End of variables declaration//GEN-END:variables
}
