package view;

import business.ExameBS;
import swing.SwingFrm;

/**
 *
 * @author nilton.brito
 */
public class FrmExames extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmExames frmExames;

    // Método gerenciador de janelas abertas
    public static FrmExames getInstancia() {
        if (frmExames == null) {
            frmExames = new FrmExames();
        }
        return frmExames;
    }

    SwingFrm swingFrm = new SwingFrm();
    ExameBS exameBS = new ExameBS();

    /**
     * Creates new form FrmExames
     */
    public FrmExames() {
        initComponents();

        jTableFrmExamePesquisaAtleta.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        jTableFrmExamePesquisaAtleta.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());
        jTableFrmExamePesquisaExame.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        jTableFrmExamePesquisaExame.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());

        txtIdGeral.setVisible(false);
        lbIdGeral.setVisible(false);
        txtIdExame.setVisible(false);
        lbIdExame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupExame = new javax.swing.ButtonGroup();
        painelPrincipal = new javax.swing.JPanel();
        painelCadastroExame = new javax.swing.JPanel();
        txtIdAtleta = new app.bolivia.swing.JCTextField();
        lbIdAtleta = new swing.JLabelBordas();
        txtNomeAtletaExame = new app.bolivia.swing.JCTextField();
        lbNomeAtletaExame = new swing.JLabelBordas();
        cmbClubeExame = new org.bolivia.combo.SComboBoxBlue();
        lbClubeAtletaExame = new swing.JLabelBordas();
        cmbFaixaExame = new org.bolivia.combo.SComboBoxBlue();
        lbFaixaExame = new swing.JLabelBordas();
        txtDataExame = new javax.swing.JFormattedTextField();
        lbDataExame = new swing.JLabelBordas();
        btnAdicionarExame = new javax.swing.JButton();
        btnEditarDataExame = new javax.swing.JButton();
        btnApagarExame = new javax.swing.JButton();
        btnLimparPesquisaExame = new javax.swing.JButton();
        btnImprimirExame = new javax.swing.JButton();
        txtIdGeral = new app.bolivia.swing.JCTextField();
        lbIdGeral = new swing.JLabelBordas();
        txtTotalExame = new app.bolivia.swing.JCTextField();
        lbTotalExame = new swing.JLabelBordas();
        btnPesquisarExame = new javax.swing.JButton();
        txtIdExame = new app.bolivia.swing.JCTextField();
        lbIdExame = new swing.JLabelBordas();
        jScrollPanePesquisaExame = new javax.swing.JScrollPane();
        jTableFrmExamePesquisaExame = new javax.swing.JTable();
        painelPesquisar = new javax.swing.JPanel();
        txtPesquisar = new app.bolivia.swing.JCTextField();
        lbPesquisar = new swing.JLabelBordas();
        jScrollPanePesquisaAtleta = new javax.swing.JScrollPane();
        jTableFrmExamePesquisaAtleta = new javax.swing.JTable();
        txtTotalAtleta = new app.bolivia.swing.JCTextField();
        lbTotalAtleta = new swing.JLabelBordas();
        painelExame = new javax.swing.JPanel();
        jRadioBtnDangayExame = new javax.swing.JRadioButton();
        jRadioBtnYudanshaExame = new javax.swing.JRadioButton();
        jRadioBtnCBKSCExame = new javax.swing.JRadioButton();

        setTitle("CADASTRO DE EXAME");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1348, 623));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelCadastroExame.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroExame.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRAR EXAMES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelCadastroExame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtIdAtleta.setBorder(null);
        txtIdAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdAtleta.setToolTipText("");
        txtIdAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdAtleta.setPlaceholder("ID ATLETA");
        txtIdAtleta.setVerifyInputWhenFocusTarget(false);
        txtIdAtleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdAtletaKeyReleased(evt);
            }
        });
        painelCadastroExame.add(txtIdAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        lbIdAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbIdAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbIdAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbIdAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbIdAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 50));

        txtNomeAtletaExame.setBackground(new java.awt.Color(34, 102, 145));
        txtNomeAtletaExame.setBorder(null);
        txtNomeAtletaExame.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeAtletaExame.setToolTipText("");
        txtNomeAtletaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeAtletaExame.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomeAtletaExame.setPlaceholder("NOME DO ALUNO(A)");
        txtNomeAtletaExame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAtletaExameKeyReleased(evt);
            }
        });
        painelCadastroExame.add(txtNomeAtletaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 340, 30));

        lbNomeAtletaExame.setBackground(new java.awt.Color(34, 102, 145));
        lbNomeAtletaExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbNomeAtletaExame.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeAtletaExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNomeAtletaExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/user.png"))); // NOI18N
        lbNomeAtletaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomeAtletaExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbNomeAtletaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 400, 50));

        cmbClubeExame.setBackground(new java.awt.Color(34, 102, 145));
        cmbClubeExame.setBorder(null);
        cmbClubeExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbClubeExame.setOpaque(false);
        cmbClubeExame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClubeExameItemStateChanged(evt);
            }
        });
        painelCadastroExame.add(cmbClubeExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 310, -1));

        lbClubeAtletaExame.setBackground(new java.awt.Color(34, 102, 145));
        lbClubeAtletaExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbClubeAtletaExame.setForeground(new java.awt.Color(255, 255, 255));
        lbClubeAtletaExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbClubeAtletaExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/clube.png"))); // NOI18N
        lbClubeAtletaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClubeAtletaExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbClubeAtletaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 380, 50));

        cmbFaixaExame.setBackground(new java.awt.Color(34, 102, 145));
        cmbFaixaExame.setBorder(null);
        cmbFaixaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbFaixaExame.setOpaque(false);
        cmbFaixaExame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFaixaExameItemStateChanged(evt);
            }
        });
        painelCadastroExame.add(cmbFaixaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 120, -1));

        lbFaixaExame.setBackground(new java.awt.Color(34, 102, 145));
        lbFaixaExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbFaixaExame.setForeground(new java.awt.Color(255, 255, 255));
        lbFaixaExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbFaixaExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/faixa-1.png"))); // NOI18N
        lbFaixaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbFaixaExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbFaixaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 190, 50));

        txtDataExame.setBackground(new java.awt.Color(34, 102, 145));
        txtDataExame.setBorder(null);
        txtDataExame.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataExame.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDataExame.setSelectionColor(new java.awt.Color(35, 102, 145));
        painelCadastroExame.add(txtDataExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 120, 30));

        lbDataExame.setBackground(new java.awt.Color(34, 102, 145));
        lbDataExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbDataExame.setForeground(new java.awt.Color(255, 255, 255));
        lbDataExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbDataExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/calendar_clock.png"))); // NOI18N
        lbDataExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbDataExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 180, 50));

        btnAdicionarExame.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionarExame.setForeground(new java.awt.Color(35, 102, 145));
        btnAdicionarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-50px.png"))); // NOI18N
        btnAdicionarExame.setText("ADICIONAR");
        btnAdicionarExame.setToolTipText("Adicionar data do Exame");
        btnAdicionarExame.setBorder(null);
        btnAdicionarExame.setBorderPainted(false);
        btnAdicionarExame.setContentAreaFilled(false);
        btnAdicionarExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarExame.setEnabled(false);
        btnAdicionarExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionarExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-50px.png"))); // NOI18N
        btnAdicionarExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnAdicionarExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        btnEditarDataExame.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarDataExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditarDataExame.setForeground(new java.awt.Color(35, 102, 145));
        btnEditarDataExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-50px.png"))); // NOI18N
        btnEditarDataExame.setText("EDITAR");
        btnEditarDataExame.setToolTipText("Editar data do Exame");
        btnEditarDataExame.setBorder(null);
        btnEditarDataExame.setBorderPainted(false);
        btnEditarDataExame.setContentAreaFilled(false);
        btnEditarDataExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarDataExame.setEnabled(false);
        btnEditarDataExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarDataExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-50px.png"))); // NOI18N
        btnEditarDataExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarDataExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDataExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnEditarDataExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, -1, -1));

        btnApagarExame.setBackground(new java.awt.Color(255, 255, 255));
        btnApagarExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApagarExame.setForeground(new java.awt.Color(35, 102, 145));
        btnApagarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-50px.png"))); // NOI18N
        btnApagarExame.setText("APAGAR");
        btnApagarExame.setToolTipText("Apagar Exame");
        btnApagarExame.setBorder(null);
        btnApagarExame.setBorderPainted(false);
        btnApagarExame.setContentAreaFilled(false);
        btnApagarExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagarExame.setEnabled(false);
        btnApagarExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagarExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-50px.png"))); // NOI18N
        btnApagarExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnApagarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnApagarExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, -1, -1));

        btnLimparPesquisaExame.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparPesquisaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparPesquisaExame.setForeground(new java.awt.Color(35, 102, 145));
        btnLimparPesquisaExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimparPesquisaExame.setText("LIMPAR");
        btnLimparPesquisaExame.setBorder(null);
        btnLimparPesquisaExame.setBorderPainted(false);
        btnLimparPesquisaExame.setContentAreaFilled(false);
        btnLimparPesquisaExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparPesquisaExame.setEnabled(false);
        btnLimparPesquisaExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparPesquisaExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimparPesquisaExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparPesquisaExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPesquisaExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnLimparPesquisaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 80, -1, -1));

        btnImprimirExame.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimirExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimirExame.setForeground(new java.awt.Color(35, 102, 145));
        btnImprimirExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/print-1-50px.png"))); // NOI18N
        btnImprimirExame.setText("IMPRIMIR");
        btnImprimirExame.setToolTipText("Imprimir Exame");
        btnImprimirExame.setBorder(null);
        btnImprimirExame.setBorderPainted(false);
        btnImprimirExame.setContentAreaFilled(false);
        btnImprimirExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimirExame.setEnabled(false);
        btnImprimirExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/print-2-50px.png"))); // NOI18N
        btnImprimirExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnImprimirExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, -1, -1));

        txtIdGeral.setEditable(false);
        txtIdGeral.setBackground(new java.awt.Color(34, 102, 145));
        txtIdGeral.setBorder(null);
        txtIdGeral.setForeground(new java.awt.Color(255, 255, 255));
        txtIdGeral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdGeral.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdGeral.setPlaceholder("ID GERAL");
        painelCadastroExame.add(txtIdGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 70, 30));

        lbIdGeral.setBackground(new java.awt.Color(34, 102, 145));
        lbIdGeral.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdGeral.setForeground(new java.awt.Color(255, 255, 255));
        lbIdGeral.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbIdGeral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdGeral.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbIdGeral.setRequestFocusEnabled(false);
        painelCadastroExame.add(lbIdGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 140, 50));

        txtTotalExame.setEditable(false);
        txtTotalExame.setBackground(new java.awt.Color(34, 102, 145));
        txtTotalExame.setBorder(null);
        txtTotalExame.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalExame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalExame.setToolTipText("");
        txtTotalExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalExame.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalExame.setPlaceholder("TOTAL EXAMES");
        txtTotalExame.setVerifyInputWhenFocusTarget(false);
        painelCadastroExame.add(txtTotalExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        lbTotalExame.setBackground(new java.awt.Color(34, 102, 145));
        lbTotalExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbTotalExame.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotalExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelCadastroExame.add(lbTotalExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 50));

        btnPesquisarExame.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisarExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisarExame.setForeground(new java.awt.Color(35, 102, 145));
        btnPesquisarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-1-50px.png"))); // NOI18N
        btnPesquisarExame.setText("PESQUISAR");
        btnPesquisarExame.setToolTipText("Adicionar data do Exame");
        btnPesquisarExame.setBorder(null);
        btnPesquisarExame.setBorderPainted(false);
        btnPesquisarExame.setContentAreaFilled(false);
        btnPesquisarExame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarExame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-2-50px.png"))); // NOI18N
        btnPesquisarExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarExameActionPerformed(evt);
            }
        });
        painelCadastroExame.add(btnPesquisarExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        txtIdExame.setEditable(false);
        txtIdExame.setBackground(new java.awt.Color(34, 102, 145));
        txtIdExame.setBorder(null);
        txtIdExame.setForeground(new java.awt.Color(255, 255, 255));
        txtIdExame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdExame.setPhColor(new java.awt.Color(255, 255, 255));
        txtIdExame.setPlaceholder("ID EXAME");
        painelCadastroExame.add(txtIdExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 70, 30));

        lbIdExame.setBackground(new java.awt.Color(34, 102, 145));
        lbIdExame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbIdExame.setForeground(new java.awt.Color(255, 255, 255));
        lbIdExame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbIdExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbIdExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbIdExame.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbIdExame.setRequestFocusEnabled(false);
        painelCadastroExame.add(lbIdExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, 50));

        painelPrincipal.add(painelCadastroExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1320, 160));

        jScrollPanePesquisaExame.setPreferredSize(new java.awt.Dimension(500, 161));

        jTableFrmExamePesquisaExame = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        jTableFrmExamePesquisaExame.setBackground(new java.awt.Color(255, 255, 255));
        jTableFrmExamePesquisaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableFrmExamePesquisaExame.setForeground(new java.awt.Color(35, 102, 145));
        jTableFrmExamePesquisaExame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ALUNO(A)", "CLUBE", "FAIXA", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFrmExamePesquisaExame.setGridColor(new java.awt.Color(204, 204, 255));
        jTableFrmExamePesquisaExame.setSelectionBackground(new java.awt.Color(0, 103, 139));
        jTableFrmExamePesquisaExame.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableFrmExamePesquisaExame.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFrmExamePesquisaExame.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFrmExamePesquisaExame.getTableHeader().setReorderingAllowed(false);
        jTableFrmExamePesquisaExame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFrmExamePesquisaExameMouseClicked(evt);
            }
        });
        jScrollPanePesquisaExame.setViewportView(jTableFrmExamePesquisaExame);
        if (jTableFrmExamePesquisaExame.getColumnModel().getColumnCount() > 0) {
            jTableFrmExamePesquisaExame.getColumnModel().getColumn(4).setHeaderValue("DATA");
        }

        painelPrincipal.add(jScrollPanePesquisaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1320, 250));

        painelPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        painelPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(34, 102, 145))); // NOI18N
        painelPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        txtPesquisar.setBorder(null);
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPesquisar.setPhColor(new java.awt.Color(255, 255, 255));
        txtPesquisar.setPlaceholder("ID/NOME ATLETA");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painelPesquisar.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 30));

        lbPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        lbPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/search2.png"))); // NOI18N
        lbPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisar.add(lbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 50));

        jScrollPanePesquisaAtleta.setPreferredSize(new java.awt.Dimension(500, 161));

        jTableFrmExamePesquisaAtleta = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        jTableFrmExamePesquisaAtleta.setBackground(new java.awt.Color(255, 255, 255));
        jTableFrmExamePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableFrmExamePesquisaAtleta.setForeground(new java.awt.Color(35, 102, 145));
        jTableFrmExamePesquisaAtleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ALUNO(A)", "CLUBE", "FAIXA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFrmExamePesquisaAtleta.setGridColor(new java.awt.Color(204, 204, 255));
        jTableFrmExamePesquisaAtleta.setSelectionBackground(new java.awt.Color(0, 103, 139));
        jTableFrmExamePesquisaAtleta.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableFrmExamePesquisaAtleta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFrmExamePesquisaAtleta.getTableHeader().setReorderingAllowed(false);
        jTableFrmExamePesquisaAtleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFrmExamePesquisaAtletaMouseClicked(evt);
            }
        });
        jScrollPanePesquisaAtleta.setViewportView(jTableFrmExamePesquisaAtleta);

        painelPesquisar.add(jScrollPanePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 900, 130));

        txtTotalAtleta.setEditable(false);
        txtTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtTotalAtleta.setBorder(null);
        txtTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAtleta.setToolTipText("");
        txtTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setPlaceholder("TOTAL ATLETAS");
        txtTotalAtleta.setVerifyInputWhenFocusTarget(false);
        painelPesquisar.add(txtTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 110, 30));

        lbTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbTotalAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotalAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisar.add(lbTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 130, 50));

        painelExame.setBackground(new java.awt.Color(255, 255, 255));
        painelExame.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SELECIONE O TIPO DE ATLETA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelExame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioBtnDangayExame.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupExame.add(jRadioBtnDangayExame);
        jRadioBtnDangayExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnDangayExame.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnDangayExame.setSelected(true);
        jRadioBtnDangayExame.setText("Atleta Dangay");
        jRadioBtnDangayExame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnDangayExameItemStateChanged(evt);
            }
        });
        painelExame.add(jRadioBtnDangayExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jRadioBtnYudanshaExame.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupExame.add(jRadioBtnYudanshaExame);
        jRadioBtnYudanshaExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnYudanshaExame.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnYudanshaExame.setText("Atleta Yudansha");
        jRadioBtnYudanshaExame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnYudanshaExameItemStateChanged(evt);
            }
        });
        painelExame.add(jRadioBtnYudanshaExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 20));

        jRadioBtnCBKSCExame.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupExame.add(jRadioBtnCBKSCExame);
        jRadioBtnCBKSCExame.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioBtnCBKSCExame.setForeground(new java.awt.Color(35, 102, 145));
        jRadioBtnCBKSCExame.setText("Atleta CBKSC");
        jRadioBtnCBKSCExame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioBtnCBKSCExameItemStateChanged(evt);
            }
        });
        painelExame.add(jRadioBtnCBKSCExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 20));

        painelPesquisar.add(painelExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 70));

        painelPrincipal.add(painelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1320, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1348, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdAtletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdAtletaKeyReleased
        btnLimparPesquisaExame.setEnabled(true);
    }//GEN-LAST:event_txtIdAtletaKeyReleased

    private void txtNomeAtletaExameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAtletaExameKeyReleased
        // TODO add your handling code here:                                         
        txtNomeAtletaExame.setText(txtNomeAtletaExame.getText().toUpperCase());
        btnLimparPesquisaExame.setEnabled(true);
    }//GEN-LAST:event_txtNomeAtletaExameKeyReleased

    private void cmbClubeExameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClubeExameItemStateChanged
        // TODO add your handling code here:  
        btnLimparPesquisaExame.setEnabled(true);
    }//GEN-LAST:event_cmbClubeExameItemStateChanged

    private void cmbFaixaExameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFaixaExameItemStateChanged
        // TODO add your handling code here:
        btnLimparPesquisaExame.setEnabled(true);
    }//GEN-LAST:event_cmbFaixaExameItemStateChanged

    private void btnAdicionarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarExameActionPerformed
        exameBS.adicionar();
    }//GEN-LAST:event_btnAdicionarExameActionPerformed

    private void btnEditarDataExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDataExameActionPerformed
        exameBS.editar();
    }//GEN-LAST:event_btnEditarDataExameActionPerformed

    private void btnApagarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarExameActionPerformed
        exameBS.deletar();
    }//GEN-LAST:event_btnApagarExameActionPerformed

    private void btnLimparPesquisaExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPesquisaExameActionPerformed
        // TODO add your handling code here:
        exameBS.limparCampos();
    }//GEN-LAST:event_btnLimparPesquisaExameActionPerformed

    private void btnImprimirExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirExameActionPerformed
        exameBS.imprimirExame();
    }//GEN-LAST:event_btnImprimirExameActionPerformed

    private void jTableFrmExamePesquisaExameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFrmExamePesquisaExameMouseClicked
        exameBS.setarCampos();
        //exameBS.setarTipoAtleta();
    }//GEN-LAST:event_jTableFrmExamePesquisaExameMouseClicked

    private void jRadioBtnDangayExameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnDangayExameItemStateChanged
        swingFrm.setCmbFaixaExame();
        swingFrm.setCmbClubeExame();
    }//GEN-LAST:event_jRadioBtnDangayExameItemStateChanged

    private void jRadioBtnYudanshaExameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnYudanshaExameItemStateChanged
        swingFrm.setCmbFaixaExame();
        swingFrm.setCmbClubeExame();
    }//GEN-LAST:event_jRadioBtnYudanshaExameItemStateChanged

    private void jRadioBtnCBKSCExameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioBtnCBKSCExameItemStateChanged
        swingFrm.setCmbFaixaExame();
        swingFrm.setCmbClubeExame();
    }//GEN-LAST:event_jRadioBtnCBKSCExameItemStateChanged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        swingFrm.setCmbFaixaExame();
        swingFrm.setCmbClubeExame();
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // Chamando o metodo pesquisar clientes
        txtPesquisar.setText(txtPesquisar.getText().toUpperCase());
        exameBS.pesquisar();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void jTableFrmExamePesquisaAtletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFrmExamePesquisaAtletaMouseClicked
        exameBS.setarCamposAtleta();
        exameBS.setarTipoAtleta();
    }//GEN-LAST:event_jTableFrmExamePesquisaAtletaMouseClicked

    private void btnPesquisarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarExameActionPerformed
        exameBS.pesquisarExame();
    }//GEN-LAST:event_btnPesquisarExameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionarExame;
    public static javax.swing.JButton btnApagarExame;
    public static javax.swing.JButton btnEditarDataExame;
    public static javax.swing.JButton btnImprimirExame;
    public static javax.swing.JButton btnLimparPesquisaExame;
    public static javax.swing.JButton btnPesquisarExame;
    private javax.swing.ButtonGroup buttonGroupExame;
    public static org.bolivia.combo.SComboBoxBlue cmbClubeExame;
    public static org.bolivia.combo.SComboBoxBlue cmbFaixaExame;
    public static javax.swing.JRadioButton jRadioBtnCBKSCExame;
    public static javax.swing.JRadioButton jRadioBtnDangayExame;
    public static javax.swing.JRadioButton jRadioBtnYudanshaExame;
    private javax.swing.JScrollPane jScrollPanePesquisaAtleta;
    private javax.swing.JScrollPane jScrollPanePesquisaExame;
    public static javax.swing.JTable jTableFrmExamePesquisaAtleta;
    public static javax.swing.JTable jTableFrmExamePesquisaExame;
    private swing.JLabelBordas lbClubeAtletaExame;
    private swing.JLabelBordas lbDataExame;
    private swing.JLabelBordas lbFaixaExame;
    private swing.JLabelBordas lbIdAtleta;
    public static swing.JLabelBordas lbIdExame;
    public static swing.JLabelBordas lbIdGeral;
    private swing.JLabelBordas lbNomeAtletaExame;
    public static swing.JLabelBordas lbPesquisar;
    private swing.JLabelBordas lbTotalAtleta;
    private swing.JLabelBordas lbTotalExame;
    private javax.swing.JPanel painelCadastroExame;
    private javax.swing.JPanel painelExame;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JPanel painelPrincipal;
    public static javax.swing.JFormattedTextField txtDataExame;
    public static app.bolivia.swing.JCTextField txtIdAtleta;
    public static app.bolivia.swing.JCTextField txtIdExame;
    public static app.bolivia.swing.JCTextField txtIdGeral;
    public static app.bolivia.swing.JCTextField txtNomeAtletaExame;
    public static app.bolivia.swing.JCTextField txtPesquisar;
    public static app.bolivia.swing.JCTextField txtTotalAtleta;
    public static app.bolivia.swing.JCTextField txtTotalExame;
    // End of variables declaration//GEN-END:variables
}
