package view;

import business.PesquisaBS;
import swing.SwingFrm;

/**
 *
 * @author nilto
 */
public class FrmPesquisa extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmPesquisa frmPeaquisaAtleta;

    // Método gerenciador de janelas abertas
    public static FrmPesquisa getInstancia() {
        if (frmPeaquisaAtleta == null) {
            frmPeaquisaAtleta = new FrmPesquisa();
        }
        return frmPeaquisaAtleta;
    }

    SwingFrm swingFrm = new SwingFrm();
    PesquisaBS pesquisaBS = new PesquisaBS();

    /**
     * Creates new form FrmPeaquisaAtleta
     */
    public FrmPesquisa() {
        initComponents();

        tabelaFrmPesquisa.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaFrmPesquisa.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());

        txtNomeAtleta.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelPesquisa = new javax.swing.JPanel();
        txtTotalAtleta = new app.bolivia.swing.JCTextField();
        lbTotalAtleta = new swing.JLabelBordas();
        cmbClubePesquisaAtleta = new org.bolivia.combo.SComboBoxBlue();
        lbClubePesquisaAtleta = new swing.JLabelBordas();
        txtNomeAtleta = new app.bolivia.swing.JCTextField();
        lbNomeAtleta = new swing.JLabelBordas();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPanePesquisaAtleta = new javax.swing.JScrollPane();
        tabelaFrmPesquisa = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.black);
        setTitle("PESQUISAR ATLETA");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        painelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISA DE ATLETA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelPesquisa.setForeground(new java.awt.Color(35, 102, 145));
        painelPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTotalAtleta.setEditable(false);
        txtTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtTotalAtleta.setBorder(null);
        txtTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAtleta.setToolTipText("");
        txtTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotalAtleta.setPlaceholder("TOTAL ATLETA");
        txtTotalAtleta.setVerifyInputWhenFocusTarget(false);
        painelPesquisa.add(txtTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 33, 100, 30));

        lbTotalAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbTotalAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbTotalAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTotalAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotalAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbTotalAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, 120, 50));

        cmbClubePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        cmbClubePesquisaAtleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbClubePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbClubePesquisaAtleta.setOpaque(false);
        cmbClubePesquisaAtleta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClubePesquisaAtletaItemStateChanged(evt);
            }
        });
        painelPesquisa.add(cmbClubePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 310, -1));

        lbClubePesquisaAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbClubePesquisaAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbClubePesquisaAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbClubePesquisaAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbClubePesquisaAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/clube.png"))); // NOI18N
        lbClubePesquisaAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClubePesquisaAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbClubePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 380, 50));

        txtNomeAtleta.setBackground(new java.awt.Color(34, 102, 145));
        txtNomeAtleta.setBorder(null);
        txtNomeAtleta.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeAtleta.setToolTipText("");
        txtNomeAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNomeAtleta.setPhColor(new java.awt.Color(255, 255, 255));
        txtNomeAtleta.setPlaceholder("NOME DO ALUNO(A)");
        txtNomeAtleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAtletaKeyReleased(evt);
            }
        });
        painelPesquisa.add(txtNomeAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 320, 30));

        lbNomeAtleta.setBackground(new java.awt.Color(34, 102, 145));
        lbNomeAtleta.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lbNomeAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeAtleta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNomeAtleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/user.png"))); // NOI18N
        lbNomeAtleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNomeAtleta.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisa.add(lbNomeAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 380, 50));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(35, 102, 145));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-1-50px.png"))); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.setBorder(null);
        btnPesquisar.setBorderPainted(false);
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pesquisar-2-50px.png"))); // NOI18N
        btnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painelPesquisa.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, -1));

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(35, 102, 145));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-50px.png"))); // NOI18N
        btnLimpar.setText("LIMPAR PESQUISA");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setEnabled(false);
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-50px.png"))); // NOI18N
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelPesquisa.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 90, -1, -1));

        jScrollPanePesquisaAtleta.setPreferredSize(new java.awt.Dimension(500, 161));

        tabelaFrmPesquisa = new javax.swing.JTable(){ public boolean isCellEditable(int eowIndex, int colIndex){ return false; } };
        tabelaFrmPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        tabelaFrmPesquisa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaFrmPesquisa.setForeground(new java.awt.Color(35, 102, 145));
        tabelaFrmPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID DANGAY", "ID YUDANSHA", "ID CBKSC", "CLUBE", "ALUNO(A)", "SEXO", "IDADE", "NASCIMENTO", "CATEGORIA", "FAIXA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFrmPesquisa.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaFrmPesquisa.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaFrmPesquisa.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaFrmPesquisa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaFrmPesquisa.getTableHeader().setReorderingAllowed(false);
        jScrollPanePesquisaAtleta.setViewportView(tabelaFrmPesquisa);

        painelPesquisa.add(jScrollPanePesquisaAtleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1300, 400));

        painelPrincipal.add(painelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1320, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1348, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAtletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAtletaKeyReleased
        txtNomeAtleta.setText(txtNomeAtleta.getText().toUpperCase());
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_txtNomeAtletaKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisaBS.pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        pesquisaBS.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cmbClubePesquisaAtletaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClubePesquisaAtletaItemStateChanged
        // TODO add your handling code here:
        btnLimpar.setEnabled(true);
    }//GEN-LAST:event_cmbClubePesquisaAtletaItemStateChanged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        swingFrm.setFrmPesquisaAtleta();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnLimpar;
    public static javax.swing.JButton btnPesquisar;
    public static org.bolivia.combo.SComboBoxBlue cmbClubePesquisaAtleta;
    private javax.swing.JScrollPane jScrollPanePesquisaAtleta;
    private swing.JLabelBordas lbClubePesquisaAtleta;
    private swing.JLabelBordas lbNomeAtleta;
    private swing.JLabelBordas lbTotalAtleta;
    private javax.swing.JPanel painelPesquisa;
    private javax.swing.JPanel painelPrincipal;
    public static javax.swing.JTable tabelaFrmPesquisa;
    public static app.bolivia.swing.JCTextField txtNomeAtleta;
    public static app.bolivia.swing.JCTextField txtTotalAtleta;
    // End of variables declaration//GEN-END:variables
}
