package view;

import Atxy2k.CustomTextField.RestrictedTextField;
import business.UsuarioBS;
import swing.SwingFrm;

/**
 *
 * @author nilton.brito
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    // Atributo identificador de janelas abertas
    public static FrmUsuarios frmUsuario;

    // Método gerenciador de janelas abertas
    public static FrmUsuarios getInstancia() {
        if (frmUsuario == null) {
            frmUsuario = new FrmUsuarios();
        }
        return frmUsuario;
    }

    SwingFrm swingFrm = new SwingFrm();
    UsuarioBS usuarioBS = new UsuarioBS();

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
        RestrictedTextField validarMatricula;
        validarMatricula = new RestrictedTextField(txtMatricula);
        //validarMatricula.setOnlyNums(true);
        validarMatricula.setLimit(6);
        RestrictedTextField validarUsuario;
        validarUsuario = new RestrictedTextField(txtNome);
        validarUsuario.setLimit(50);
        RestrictedTextField validarLogin;
        validarLogin = new RestrictedTextField(txtLogin);
        validarLogin.setLimit(20);
        RestrictedTextField validarSenha;
        validarSenha = new RestrictedTextField(txtSenha);
        validarSenha.setLimit(15);

        txtId.setVisible(false);
        lbId.setVisible(false);
        tabelaUsuario.getTableHeader().setDefaultRenderer(new swing.EstiloTabelaHeader());
        tabelaUsuario.setDefaultRenderer(Object.class, new swing.EstiloTabelaRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customUI1 = new org.bolivia.combo.CustomUI();
        painelPrinciapl = new javax.swing.JPanel();
        painelPesquisar = new swing.PainelBordas();
        txtPesquisar = new app.bolivia.swing.JCTextField();
        lbPesquisar = new swing.JLabelBordas();
        painelOpcoes = new swing.PainelBordas();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        painelRegistro = new swing.PainelBordas();
        txtMatricula = new app.bolivia.swing.JCTextField();
        lbMatricula = new swing.JLabelBordas();
        txtNome = new app.bolivia.swing.JCTextField();
        lbNome = new swing.JLabelBordas();
        txtCpf = new javax.swing.JFormattedTextField();
        lbCpf = new swing.JLabelBordas();
        txtCelular = new javax.swing.JFormattedTextField();
        lbCelular = new swing.JLabelBordas();
        cmbSexoUsuario = new org.bolivia.combo.SComboBoxBlue();
        lbSexoUsuario = new swing.JLabelBordas();
        cmbPerfil = new org.bolivia.combo.SComboBoxBlue();
        lbPerfil = new swing.JLabelBordas();
        txtDataCad = new app.bolivia.swing.JCTextField();
        lbDataCad = new swing.JLabelBordas();
        painelLogin = new javax.swing.JPanel();
        txtLogin = new app.bolivia.swing.JCTextField();
        lbLogin = new swing.JLabelBordas();
        txtSenha = new jpass.JRPasswordField();
        lbSenha = new swing.JLabelBordas();
        cmbStatus = new org.bolivia.combo.SComboBoxBlue();
        lbStatus = new swing.JLabelBordas();
        jCheckSenha = new javax.swing.JCheckBox();
        txtId = new app.bolivia.swing.JCTextField();
        lbId = new swing.JLabelBordas();

        setClosable(true);
        setTitle("CADASTRO DE USUÁRIOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1348, 623));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrinciapl.setBackground(new java.awt.Color(255, 255, 255));
        painelPrinciapl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        painelPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelPesquisar.setForeground(new java.awt.Color(35, 102, 145));
        painelPesquisar.setPreferredSize(new java.awt.Dimension(518, 130));
        painelPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        txtPesquisar.setBorder(null);
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPesquisar.setPhColor(new java.awt.Color(255, 255, 255));
        txtPesquisar.setPlaceholder("MATRICULA/NOME");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painelPesquisar.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 30));

        lbPesquisar.setBackground(new java.awt.Color(34, 102, 145));
        lbPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/search2.png"))); // NOI18N
        lbPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPesquisar.add(lbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, 50));

        painelPrinciapl.add(painelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 180, 340, 130));

        painelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelOpcoes.setForeground(new java.awt.Color(35, 102, 145));
        painelOpcoes.setPreferredSize(new java.awt.Dimension(800, 130));
        painelOpcoes.setLayout(new java.awt.GridLayout());

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(35, 102, 145));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-1-75px.png"))); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setBorder(null);
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setContentAreaFilled(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/adicionar-2-75px.png"))); // NOI18N
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnAdicionar);

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(35, 102, 145));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-1-75px.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setEnabled(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/editar-2-75px.png"))); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEditar);

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(35, 102, 145));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-1-75px.png"))); // NOI18N
        btnDeletar.setText("APAGAR");
        btnDeletar.setBorder(null);
        btnDeletar.setBorderPainted(false);
        btnDeletar.setContentAreaFilled(false);
        btnDeletar.setEnabled(false);
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/apagar-2-75px.png"))); // NOI18N
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnDeletar);

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(35, 102, 145));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-1-75px.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setEnabled(false);
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/limpar-2-75px.png"))); // NOI18N
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnLimpar);

        painelPrinciapl.add(painelOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 490, 130));

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane.setAutoscrolls(true);
        jScrollPane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tabelaUsuario = new javax.swing.JTable(){
            public boolean isCellEditable(int eowIndex, int colIndex){
                return false;
            }
        };
        tabelaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tabelaUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MATRICULA", "NOME", "CPF", "CELULAR", "SEXO", "PERFIL", "LOGIN", "STATUS", "DATA DE CADASTRO", "DATA DE ATUALIZAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuario.setFocusable(false);
        tabelaUsuario.setGridColor(new java.awt.Color(204, 204, 255));
        tabelaUsuario.setSelectionBackground(new java.awt.Color(0, 103, 139));
        tabelaUsuario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaUsuario.getTableHeader().setReorderingAllowed(false);
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tabelaUsuario);

        painelPrinciapl.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 314, 1310, 260));

        painelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        painelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelRegistro.setPreferredSize(new java.awt.Dimension(1324, 166));
        painelRegistro.setRequestFocusEnabled(false);
        painelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMatricula.setBackground(new java.awt.Color(34, 102, 145));
        txtMatricula.setBorder(null);
        txtMatricula.setForeground(new java.awt.Color(255, 255, 255));
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMatricula.setPhColor(new java.awt.Color(255, 255, 255));
        txtMatricula.setPlaceholder("MATRICULA");
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyReleased(evt);
            }
        });
        painelRegistro.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 30));

        lbMatricula.setBackground(new java.awt.Color(34, 102, 145));
        lbMatricula.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbMatricula.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cracha.png"))); // NOI18N
        lbMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 50));

        txtNome.setBackground(new java.awt.Color(34, 102, 145));
        txtNome.setBorder(null);
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNome.setPhColor(new java.awt.Color(255, 255, 255));
        txtNome.setPlaceholder("NOME USUÁRIO");
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        painelRegistro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 380, 30));

        lbNome.setBackground(new java.awt.Color(34, 102, 145));
        lbNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/user.png"))); // NOI18N
        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 450, 50));

        txtCpf.setBackground(new java.awt.Color(34, 102, 145));
        txtCpf.setBorder(null);
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelRegistro.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 120, 30));

        lbCpf.setBackground(new java.awt.Color(34, 102, 145));
        lbCpf.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbCpf.setForeground(new java.awt.Color(255, 255, 255));
        lbCpf.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/cpf.png"))); // NOI18N
        lbCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCpf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 200, 50));

        txtCelular.setBackground(new java.awt.Color(34, 102, 145));
        txtCelular.setBorder(null);
        txtCelular.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelRegistro.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 30));

        lbCelular.setBackground(new java.awt.Color(34, 102, 145));
        lbCelular.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbCelular.setForeground(new java.awt.Color(255, 255, 255));
        lbCelular.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/phone.png"))); // NOI18N
        lbCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCelular.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 50));

        cmbSexoUsuario.setBackground(new java.awt.Color(34, 102, 145));
        cmbSexoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbSexoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbSexoUsuario.setOpaque(false);
        painelRegistro.add(cmbSexoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        lbSexoUsuario.setBackground(new java.awt.Color(34, 102, 145));
        lbSexoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbSexoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbSexoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSexoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/sexo.png"))); // NOI18N
        lbSexoUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSexoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbSexoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 50));

        cmbPerfil.setBackground(new java.awt.Color(34, 102, 145));
        cmbPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ADMINISTRADOR", "GERENTE", "PROFESSOR", "USUARIO" }));
        cmbPerfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbPerfil.setOpaque(false);
        painelRegistro.add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 150, -1));

        lbPerfil.setBackground(new java.awt.Color(34, 102, 145));
        lbPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbPerfil.setForeground(new java.awt.Color(255, 255, 255));
        lbPerfil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/perfil.png"))); // NOI18N
        lbPerfil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 220, 50));

        txtDataCad.setEditable(false);
        txtDataCad.setBackground(new java.awt.Color(34, 102, 145));
        txtDataCad.setBorder(null);
        txtDataCad.setForeground(new java.awt.Color(255, 255, 255));
        txtDataCad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataCad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDataCad.setPhColor(new java.awt.Color(255, 255, 255));
        txtDataCad.setPlaceholder("DATA DE CADASTRO");
        painelRegistro.add(txtDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 140, 30));

        lbDataCad.setBackground(new java.awt.Color(34, 102, 145));
        lbDataCad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbDataCad.setForeground(new java.awt.Color(255, 255, 255));
        lbDataCad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbDataCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/calendar_clock.png"))); // NOI18N
        lbDataCad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataCad.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelRegistro.add(lbDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 200, 50));

        painelPrinciapl.add(painelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, -1));

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(35, 102, 145))); // NOI18N
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setBackground(new java.awt.Color(34, 102, 145));
        txtLogin.setBorder(null);
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLogin.setPhColor(new java.awt.Color(255, 255, 255));
        txtLogin.setPlaceholder("LOGIN");
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginKeyReleased(evt);
            }
        });
        painelLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 30));

        lbLogin.setBackground(new java.awt.Color(34, 102, 145));
        lbLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/login.png"))); // NOI18N
        lbLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelLogin.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 50));

        txtSenha.setBackground(new java.awt.Color(34, 102, 145));
        txtSenha.setBorder(null);
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSenha.setPhColor(new java.awt.Color(255, 255, 255));
        txtSenha.setPlaceholder("SENHA");
        painelLogin.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 130, 30));

        lbSenha.setBackground(new java.awt.Color(34, 102, 145));
        lbSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/senha.png"))); // NOI18N
        lbSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSenha.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelLogin.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, 50));

        cmbStatus.setBackground(new java.awt.Color(34, 102, 145));
        cmbStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 102, 145), 1, true));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ATIVO", "INATIVO" }));
        cmbStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbStatus.setOpaque(false);
        painelLogin.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        lbStatus.setBackground(new java.awt.Color(34, 102, 145));
        lbStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/statusATV.png"))); // NOI18N
        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelLogin.add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 50));

        jCheckSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckSenha.setForeground(new java.awt.Color(35, 102, 145));
        jCheckSenha.setText("Reset senha");
        jCheckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSenhaActionPerformed(evt);
            }
        });
        painelLogin.add(jCheckSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        painelPrinciapl.add(painelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 440, 170));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(34, 102, 145));
        txtId.setBorder(null);
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setToolTipText("");
        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId.setPhColor(new java.awt.Color(255, 255, 255));
        txtId.setPlaceholder("ID");
        painelPrinciapl.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 30));

        lbId.setBackground(new java.awt.Color(34, 102, 145));
        lbId.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbId.setForeground(new java.awt.Color(255, 255, 255));
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/id-1.png"))); // NOI18N
        lbId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbId.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        painelPrinciapl.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrinciapl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrinciapl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1348, 623);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Chamando o metodo para adicionar
        usuarioBS.adicionarUsuario();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Chamando o metodo para editar
        usuarioBS.editarUsuario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // Chamando o metodo para deletar
        usuarioBS.deletarUsuario();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Chamando o metodo para limpar os campos
        usuarioBS.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyReleased
        txtMatricula.setText(txtMatricula.getText().toUpperCase());
    }//GEN-LAST:event_txtMatriculaKeyReleased

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        txtNome.setText(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyReleased
        txtLogin.setText(txtLogin.getText().toUpperCase());
    }//GEN-LAST:event_txtLoginKeyReleased

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // Chamando o metodo pesquisar usuarios
        txtPesquisar.setText(txtPesquisar.getText().toUpperCase());
        usuarioBS.pesquisarUsuario();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        swingFrm.setComboBoxFrmUsuario();
    }//GEN-LAST:event_formInternalFrameActivated

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        // TODO add your handling code here:
        usuarioBS.setarCampos();
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    private void jCheckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSenhaActionPerformed
        txtSenha.setEditable(true);
        txtSenha.requestFocus();
    }//GEN-LAST:event_jCheckSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnLimpar;
    public static org.bolivia.combo.SComboBoxBlue cmbPerfil;
    public static org.bolivia.combo.SComboBoxBlue cmbSexoUsuario;
    public static org.bolivia.combo.SComboBoxBlue cmbStatus;
    private org.bolivia.combo.CustomUI customUI1;
    public static javax.swing.JCheckBox jCheckSenha;
    private javax.swing.JScrollPane jScrollPane;
    private swing.JLabelBordas lbCelular;
    private swing.JLabelBordas lbCpf;
    private swing.JLabelBordas lbDataCad;
    private swing.JLabelBordas lbId;
    private swing.JLabelBordas lbLogin;
    private swing.JLabelBordas lbMatricula;
    private swing.JLabelBordas lbNome;
    public static swing.JLabelBordas lbPerfil;
    private swing.JLabelBordas lbPesquisar;
    private swing.JLabelBordas lbSenha;
    public static swing.JLabelBordas lbSexoUsuario;
    public static swing.JLabelBordas lbStatus;
    private javax.swing.JPanel painelLogin;
    private swing.PainelBordas painelOpcoes;
    private swing.PainelBordas painelPesquisar;
    private javax.swing.JPanel painelPrinciapl;
    private swing.PainelBordas painelRegistro;
    public static javax.swing.JTable tabelaUsuario;
    public static javax.swing.JFormattedTextField txtCelular;
    public static javax.swing.JFormattedTextField txtCpf;
    public static app.bolivia.swing.JCTextField txtDataCad;
    public static app.bolivia.swing.JCTextField txtId;
    public static app.bolivia.swing.JCTextField txtLogin;
    public static app.bolivia.swing.JCTextField txtMatricula;
    public static app.bolivia.swing.JCTextField txtNome;
    public static app.bolivia.swing.JCTextField txtPesquisar;
    public static jpass.JRPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
