package view;

import business.LogarBS;
import conexao.ConexaoDB;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nilton.brito
 */
public class TelaLogin extends javax.swing.JFrame {

    TelaSplash inicio;
    Connection conectar;
    LogarBS logar = new LogarBS();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));  //  Remove background
    }

    public TelaLogin(TelaSplash inicio) {
        this.inicio = inicio;
        setProgresso(0, "Carregando componentes do sistema");
        initComponents();

        setProgresso(20, "Conectando ao banco de dados!");
        conectar = ConexaoDB.conectar();
        if (conectar != null) {
            setProgresso(40, "Carregando os módulos");
            setProgresso(60, "Carregamento de módulos concluidos");
            setProgresso(80, "Carregando interfaces");
            setProgresso(90, "Interface carregada");
            setProgresso(100, "Bem vindo ao sistema!!");
        }

        setBackground(new Color(0, 0, 0, 0));  //  Remove background
    }

    void setProgresso(int percent, String informacao) {
        inicio.getJLabelProgresso().setText(informacao);
        inicio.getJBarProgresso().setValue(percent);
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            JOptionPane.showMessageDialog(this, "Não foi possível carregar a inicialização");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBordas = new swing.PainelBordas();
        painelImagem = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        painelDados = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        txtUsuario = new app.bolivia.swing.JCTextField();
        lbUsuario = new swing.JLabelBordas();
        txtSenha = new jpass.JRPasswordField();
        lbSenha = new swing.JLabelBordas();
        alertaCapsLook = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(TelaLogin.class.getResource("/imagens/principal/icon-50px.png")));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 520));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelBordas.setBackground(new java.awt.Color(242, 242, 242));

        painelImagem.setOpaque(false);
        painelImagem.setPreferredSize(new java.awt.Dimension(400, 206));

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/imagemLogin.png"))); // NOI18N

        javax.swing.GroupLayout painelImagemLayout = new javax.swing.GroupLayout(painelImagem);
        painelImagem.setLayout(painelImagemLayout);
        painelImagemLayout.setHorizontalGroup(
            painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelImagemLayout.setVerticalGroup(
            painelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelCentral.setOpaque(false);

        painelDados.setOpaque(false);
        painelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/user.png"))); // NOI18N
        painelDados.add(lbFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 200));

        txtUsuario.setBackground(new java.awt.Color(34, 102, 145));
        txtUsuario.setBorder(null);
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUsuario.setPhColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setPlaceholder("USUÁRIO");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        painelDados.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, 30));

        lbUsuario.setBackground(new java.awt.Color(34, 102, 145));
        lbUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginUs.png"))); // NOI18N
        painelDados.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 50));

        txtSenha.setBackground(new java.awt.Color(34, 102, 145));
        txtSenha.setBorder(null);
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSenha.setPhColor(new java.awt.Color(255, 255, 255));
        txtSenha.setPlaceholder("SENHA");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });
        painelDados.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 30));

        lbSenha.setBackground(new java.awt.Color(34, 102, 145));
        lbSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/campoLoginPass.png"))); // NOI18N
        painelDados.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, 50));

        alertaCapsLook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alertaCapsLook.setForeground(new java.awt.Color(153, 0, 0));
        painelDados.add(alertaCapsLook, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 15));

        painelRodape.setOpaque(false);

        btnEntrar.setBackground(new Color(0,0,0,0));
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar1.png"))); // NOI18N
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/entrar2.png"))); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        painelRodape.add(btnEntrar);

        btnSair.setBackground(new Color(0,0,0,0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair1.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/sair2.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        painelRodape.add(btnSair);

        javax.swing.GroupLayout painelCentralLayout = new javax.swing.GroupLayout(painelCentral);
        painelCentral.setLayout(painelCentralLayout);
        painelCentralLayout.setHorizontalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCentralLayout.setVerticalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentralLayout.createSequentialGroup()
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(painelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelBordasLayout = new javax.swing.GroupLayout(painelBordas);
        painelBordas.setLayout(painelBordasLayout);
        painelBordasLayout.setHorizontalGroup(
            painelBordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBordasLayout.setVerticalGroup(
            painelBordasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBordasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(painelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(painelBordas);

        setSize(new java.awt.Dimension(400, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        //Chamando o metodo logar
        logar.logarBS();
        if (logar.validar == 1) {
            this.dispose();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        txtUsuario.setText(txtUsuario.getText().toUpperCase());
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        // TODO add your handling code here:
        logar.capsLockStatus();
    }//GEN-LAST:event_txtSenhaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel alertaCapsLook;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbLogo;
    private swing.JLabelBordas lbSenha;
    private swing.JLabelBordas lbUsuario;
    private swing.PainelBordas painelBordas;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelImagem;
    private javax.swing.JPanel painelRodape;
    public static jpass.JRPasswordField txtSenha;
    public static app.bolivia.swing.JCTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
